#ifndef CLAVA_PROTO_SUPPORT_H
#define CLAVA_PROTO_SUPPORT_H

#include "ProtoObjects.h"
#include "../Clang/ClangNodes.h"
#include "../ClangEnums/ClangEnums.h"
#include "clang/AST/AST.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Attrs.inc"
#include <functional>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace clava::proto {
namespace obj = ::astwire::v1obj;

template <class E> E enumValue(std::string_view name);

template <class E> E enumValue(std::string_view name) {
  throw std::invalid_argument("Unsupported wire enum conversion for: " +
                              std::string(name));
}
template <> inline obj::TopLevelKind enumValue<obj::TopLevelKind>(std::string_view name) {
  if (name == "Decl") return static_cast<obj::TopLevelKind>(0);
  if (name == "Type") return static_cast<obj::TopLevelKind>(1);
  if (name == "Attr") return static_cast<obj::TopLevelKind>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::AttributeKind enumValue<obj::AttributeKind>(std::string_view name) {
  if (name == "AddressSpace") return static_cast<obj::AttributeKind>(0);
  if (name == "AnnotateType") return static_cast<obj::AttributeKind>(1);
  if (name == "ArmIn") return static_cast<obj::AttributeKind>(2);
  if (name == "ArmInOut") return static_cast<obj::AttributeKind>(3);
  if (name == "ArmMveStrictPolymorphism") return static_cast<obj::AttributeKind>(4);
  if (name == "ArmOut") return static_cast<obj::AttributeKind>(5);
  if (name == "ArmPreserves") return static_cast<obj::AttributeKind>(6);
  if (name == "ArmStreaming") return static_cast<obj::AttributeKind>(7);
  if (name == "ArmStreamingCompatible") return static_cast<obj::AttributeKind>(8);
  if (name == "BTFTypeTag") return static_cast<obj::AttributeKind>(9);
  if (name == "CmseNSCall") return static_cast<obj::AttributeKind>(10);
  if (name == "HLSLGroupSharedAddressSpace") return static_cast<obj::AttributeKind>(11);
  if (name == "HLSLParamModifier") return static_cast<obj::AttributeKind>(12);
  if (name == "NoDeref") return static_cast<obj::AttributeKind>(13);
  if (name == "ObjCGC") return static_cast<obj::AttributeKind>(14);
  if (name == "ObjCInertUnsafeUnretained") return static_cast<obj::AttributeKind>(15);
  if (name == "ObjCKindOf") return static_cast<obj::AttributeKind>(16);
  if (name == "OpenCLConstantAddressSpace") return static_cast<obj::AttributeKind>(17);
  if (name == "OpenCLGenericAddressSpace") return static_cast<obj::AttributeKind>(18);
  if (name == "OpenCLGlobalAddressSpace") return static_cast<obj::AttributeKind>(19);
  if (name == "OpenCLGlobalDeviceAddressSpace") return static_cast<obj::AttributeKind>(20);
  if (name == "OpenCLGlobalHostAddressSpace") return static_cast<obj::AttributeKind>(21);
  if (name == "OpenCLLocalAddressSpace") return static_cast<obj::AttributeKind>(22);
  if (name == "OpenCLPrivateAddressSpace") return static_cast<obj::AttributeKind>(23);
  if (name == "Ptr32") return static_cast<obj::AttributeKind>(24);
  if (name == "Ptr64") return static_cast<obj::AttributeKind>(25);
  if (name == "SPtr") return static_cast<obj::AttributeKind>(26);
  if (name == "TypeNonNull") return static_cast<obj::AttributeKind>(27);
  if (name == "TypeNullUnspecified") return static_cast<obj::AttributeKind>(28);
  if (name == "TypeNullable") return static_cast<obj::AttributeKind>(29);
  if (name == "TypeNullableResult") return static_cast<obj::AttributeKind>(30);
  if (name == "UPtr") return static_cast<obj::AttributeKind>(31);
  if (name == "WebAssemblyFuncref") return static_cast<obj::AttributeKind>(32);
  if (name == "CodeAlign") return static_cast<obj::AttributeKind>(33);
  if (name == "FallThrough") return static_cast<obj::AttributeKind>(34);
  if (name == "Likely") return static_cast<obj::AttributeKind>(35);
  if (name == "MustTail") return static_cast<obj::AttributeKind>(36);
  if (name == "OpenCLUnrollHint") return static_cast<obj::AttributeKind>(37);
  if (name == "Unlikely") return static_cast<obj::AttributeKind>(38);
  if (name == "AlwaysInline") return static_cast<obj::AttributeKind>(39);
  if (name == "NoInline") return static_cast<obj::AttributeKind>(40);
  if (name == "NoMerge") return static_cast<obj::AttributeKind>(41);
  if (name == "Suppress") return static_cast<obj::AttributeKind>(42);
  if (name == "AArch64SVEPcs") return static_cast<obj::AttributeKind>(43);
  if (name == "AArch64VectorPcs") return static_cast<obj::AttributeKind>(44);
  if (name == "AMDGPUKernelCall") return static_cast<obj::AttributeKind>(45);
  if (name == "AcquireHandle") return static_cast<obj::AttributeKind>(46);
  if (name == "AnyX86NoCfCheck") return static_cast<obj::AttributeKind>(47);
  if (name == "CDecl") return static_cast<obj::AttributeKind>(48);
  if (name == "FastCall") return static_cast<obj::AttributeKind>(49);
  if (name == "IntelOclBicc") return static_cast<obj::AttributeKind>(50);
  if (name == "LifetimeBound") return static_cast<obj::AttributeKind>(51);
  if (name == "M68kRTD") return static_cast<obj::AttributeKind>(52);
  if (name == "MSABI") return static_cast<obj::AttributeKind>(53);
  if (name == "NSReturnsRetained") return static_cast<obj::AttributeKind>(54);
  if (name == "ObjCOwnership") return static_cast<obj::AttributeKind>(55);
  if (name == "Pascal") return static_cast<obj::AttributeKind>(56);
  if (name == "Pcs") return static_cast<obj::AttributeKind>(57);
  if (name == "PreserveAll") return static_cast<obj::AttributeKind>(58);
  if (name == "PreserveMost") return static_cast<obj::AttributeKind>(59);
  if (name == "RegCall") return static_cast<obj::AttributeKind>(60);
  if (name == "StdCall") return static_cast<obj::AttributeKind>(61);
  if (name == "SwiftAsyncCall") return static_cast<obj::AttributeKind>(62);
  if (name == "SwiftCall") return static_cast<obj::AttributeKind>(63);
  if (name == "SysVABI") return static_cast<obj::AttributeKind>(64);
  if (name == "ThisCall") return static_cast<obj::AttributeKind>(65);
  if (name == "VectorCall") return static_cast<obj::AttributeKind>(66);
  if (name == "SwiftAsyncContext") return static_cast<obj::AttributeKind>(67);
  if (name == "SwiftContext") return static_cast<obj::AttributeKind>(68);
  if (name == "SwiftErrorResult") return static_cast<obj::AttributeKind>(69);
  if (name == "SwiftIndirectResult") return static_cast<obj::AttributeKind>(70);
  if (name == "Annotate") return static_cast<obj::AttributeKind>(71);
  if (name == "CFConsumed") return static_cast<obj::AttributeKind>(72);
  if (name == "CarriesDependency") return static_cast<obj::AttributeKind>(73);
  if (name == "NSConsumed") return static_cast<obj::AttributeKind>(74);
  if (name == "NonNull") return static_cast<obj::AttributeKind>(75);
  if (name == "OSConsumed") return static_cast<obj::AttributeKind>(76);
  if (name == "PassObjectSize") return static_cast<obj::AttributeKind>(77);
  if (name == "ReleaseHandle") return static_cast<obj::AttributeKind>(78);
  if (name == "UseHandle") return static_cast<obj::AttributeKind>(79);
  if (name == "HLSLSV_DispatchThreadID") return static_cast<obj::AttributeKind>(80);
  if (name == "HLSLSV_GroupIndex") return static_cast<obj::AttributeKind>(81);
  if (name == "AMDGPUFlatWorkGroupSize") return static_cast<obj::AttributeKind>(82);
  if (name == "AMDGPUNumSGPR") return static_cast<obj::AttributeKind>(83);
  if (name == "AMDGPUNumVGPR") return static_cast<obj::AttributeKind>(84);
  if (name == "AMDGPUWavesPerEU") return static_cast<obj::AttributeKind>(85);
  if (name == "ARMInterrupt") return static_cast<obj::AttributeKind>(86);
  if (name == "AVRInterrupt") return static_cast<obj::AttributeKind>(87);
  if (name == "AVRSignal") return static_cast<obj::AttributeKind>(88);
  if (name == "AcquireCapability") return static_cast<obj::AttributeKind>(89);
  if (name == "AcquiredAfter") return static_cast<obj::AttributeKind>(90);
  if (name == "AcquiredBefore") return static_cast<obj::AttributeKind>(91);
  if (name == "AlignMac68k") return static_cast<obj::AttributeKind>(92);
  if (name == "AlignNatural") return static_cast<obj::AttributeKind>(93);
  if (name == "Aligned") return static_cast<obj::AttributeKind>(94);
  if (name == "AllocAlign") return static_cast<obj::AttributeKind>(95);
  if (name == "AllocSize") return static_cast<obj::AttributeKind>(96);
  if (name == "AlwaysDestroy") return static_cast<obj::AttributeKind>(97);
  if (name == "AnalyzerNoReturn") return static_cast<obj::AttributeKind>(98);
  if (name == "AnyX86Interrupt") return static_cast<obj::AttributeKind>(99);
  if (name == "AnyX86NoCallerSavedRegisters") return static_cast<obj::AttributeKind>(100);
  if (name == "ArcWeakrefUnavailable") return static_cast<obj::AttributeKind>(101);
  if (name == "ArgumentWithTypeTag") return static_cast<obj::AttributeKind>(102);
  if (name == "ArmBuiltinAlias") return static_cast<obj::AttributeKind>(103);
  if (name == "ArmLocallyStreaming") return static_cast<obj::AttributeKind>(104);
  if (name == "ArmNew") return static_cast<obj::AttributeKind>(105);
  if (name == "Artificial") return static_cast<obj::AttributeKind>(106);
  if (name == "AsmLabel") return static_cast<obj::AttributeKind>(107);
  if (name == "AssertCapability") return static_cast<obj::AttributeKind>(108);
  if (name == "AssertExclusiveLock") return static_cast<obj::AttributeKind>(109);
  if (name == "AssertSharedLock") return static_cast<obj::AttributeKind>(110);
  if (name == "AssumeAligned") return static_cast<obj::AttributeKind>(111);
  if (name == "Assumption") return static_cast<obj::AttributeKind>(112);
  if (name == "Availability") return static_cast<obj::AttributeKind>(113);
  if (name == "AvailableOnlyInDefaultEvalMethod") return static_cast<obj::AttributeKind>(114);
  if (name == "BPFPreserveAccessIndex") return static_cast<obj::AttributeKind>(115);
  if (name == "BPFPreserveStaticOffset") return static_cast<obj::AttributeKind>(116);
  if (name == "BTFDeclTag") return static_cast<obj::AttributeKind>(117);
  if (name == "Blocks") return static_cast<obj::AttributeKind>(118);
  if (name == "Builtin") return static_cast<obj::AttributeKind>(119);
  if (name == "C11NoReturn") return static_cast<obj::AttributeKind>(120);
  if (name == "CFAuditedTransfer") return static_cast<obj::AttributeKind>(121);
  if (name == "CFGuard") return static_cast<obj::AttributeKind>(122);
  if (name == "CFICanonicalJumpTable") return static_cast<obj::AttributeKind>(123);
  if (name == "CFReturnsNotRetained") return static_cast<obj::AttributeKind>(124);
  if (name == "CFReturnsRetained") return static_cast<obj::AttributeKind>(125);
  if (name == "CFUnknownTransfer") return static_cast<obj::AttributeKind>(126);
  if (name == "CPUDispatch") return static_cast<obj::AttributeKind>(127);
  if (name == "CPUSpecific") return static_cast<obj::AttributeKind>(128);
  if (name == "CUDAConstant") return static_cast<obj::AttributeKind>(129);
  if (name == "CUDADevice") return static_cast<obj::AttributeKind>(130);
  if (name == "CUDADeviceBuiltinSurfaceType") return static_cast<obj::AttributeKind>(131);
  if (name == "CUDADeviceBuiltinTextureType") return static_cast<obj::AttributeKind>(132);
  if (name == "CUDAGlobal") return static_cast<obj::AttributeKind>(133);
  if (name == "CUDAHost") return static_cast<obj::AttributeKind>(134);
  if (name == "CUDAInvalidTarget") return static_cast<obj::AttributeKind>(135);
  if (name == "CUDALaunchBounds") return static_cast<obj::AttributeKind>(136);
  if (name == "CUDAShared") return static_cast<obj::AttributeKind>(137);
  if (name == "CXX11NoReturn") return static_cast<obj::AttributeKind>(138);
  if (name == "CallableWhen") return static_cast<obj::AttributeKind>(139);
  if (name == "Callback") return static_cast<obj::AttributeKind>(140);
  if (name == "Capability") return static_cast<obj::AttributeKind>(141);
  if (name == "CapturedRecord") return static_cast<obj::AttributeKind>(142);
  if (name == "Cleanup") return static_cast<obj::AttributeKind>(143);
  if (name == "CmseNSEntry") return static_cast<obj::AttributeKind>(144);
  if (name == "CodeModel") return static_cast<obj::AttributeKind>(145);
  if (name == "CodeSeg") return static_cast<obj::AttributeKind>(146);
  if (name == "Cold") return static_cast<obj::AttributeKind>(147);
  if (name == "Common") return static_cast<obj::AttributeKind>(148);
  if (name == "Const") return static_cast<obj::AttributeKind>(149);
  if (name == "ConstInit") return static_cast<obj::AttributeKind>(150);
  if (name == "Constructor") return static_cast<obj::AttributeKind>(151);
  if (name == "Consumable") return static_cast<obj::AttributeKind>(152);
  if (name == "ConsumableAutoCast") return static_cast<obj::AttributeKind>(153);
  if (name == "ConsumableSetOnRead") return static_cast<obj::AttributeKind>(154);
  if (name == "Convergent") return static_cast<obj::AttributeKind>(155);
  if (name == "CoroDisableLifetimeBound") return static_cast<obj::AttributeKind>(156);
  if (name == "CoroLifetimeBound") return static_cast<obj::AttributeKind>(157);
  if (name == "CoroOnlyDestroyWhenComplete") return static_cast<obj::AttributeKind>(158);
  if (name == "CoroReturnType") return static_cast<obj::AttributeKind>(159);
  if (name == "CoroWrapper") return static_cast<obj::AttributeKind>(160);
  if (name == "CountedBy") return static_cast<obj::AttributeKind>(161);
  if (name == "DLLExport") return static_cast<obj::AttributeKind>(162);
  if (name == "DLLExportStaticLocal") return static_cast<obj::AttributeKind>(163);
  if (name == "DLLImport") return static_cast<obj::AttributeKind>(164);
  if (name == "DLLImportStaticLocal") return static_cast<obj::AttributeKind>(165);
  if (name == "Deprecated") return static_cast<obj::AttributeKind>(166);
  if (name == "Destructor") return static_cast<obj::AttributeKind>(167);
  if (name == "DiagnoseAsBuiltin") return static_cast<obj::AttributeKind>(168);
  if (name == "DiagnoseIf") return static_cast<obj::AttributeKind>(169);
  if (name == "DisableSanitizerInstrumentation") return static_cast<obj::AttributeKind>(170);
  if (name == "DisableTailCalls") return static_cast<obj::AttributeKind>(171);
  if (name == "EmptyBases") return static_cast<obj::AttributeKind>(172);
  if (name == "EnableIf") return static_cast<obj::AttributeKind>(173);
  if (name == "EnforceTCB") return static_cast<obj::AttributeKind>(174);
  if (name == "EnforceTCBLeaf") return static_cast<obj::AttributeKind>(175);
  if (name == "EnumExtensibility") return static_cast<obj::AttributeKind>(176);
  if (name == "Error") return static_cast<obj::AttributeKind>(177);
  if (name == "ExcludeFromExplicitInstantiation") return static_cast<obj::AttributeKind>(178);
  if (name == "ExclusiveTrylockFunction") return static_cast<obj::AttributeKind>(179);
  if (name == "ExternalSourceSymbol") return static_cast<obj::AttributeKind>(180);
  if (name == "Final") return static_cast<obj::AttributeKind>(181);
  if (name == "FlagEnum") return static_cast<obj::AttributeKind>(182);
  if (name == "Flatten") return static_cast<obj::AttributeKind>(183);
  if (name == "Format") return static_cast<obj::AttributeKind>(184);
  if (name == "FormatArg") return static_cast<obj::AttributeKind>(185);
  if (name == "FunctionReturnThunks") return static_cast<obj::AttributeKind>(186);
  if (name == "GNUInline") return static_cast<obj::AttributeKind>(187);
  if (name == "GuardedBy") return static_cast<obj::AttributeKind>(188);
  if (name == "GuardedVar") return static_cast<obj::AttributeKind>(189);
  if (name == "HIPManaged") return static_cast<obj::AttributeKind>(190);
  if (name == "HLSLNumThreads") return static_cast<obj::AttributeKind>(191);
  if (name == "HLSLResource") return static_cast<obj::AttributeKind>(192);
  if (name == "HLSLResourceBinding") return static_cast<obj::AttributeKind>(193);
  if (name == "HLSLShader") return static_cast<obj::AttributeKind>(194);
  if (name == "Hot") return static_cast<obj::AttributeKind>(195);
  if (name == "IBAction") return static_cast<obj::AttributeKind>(196);
  if (name == "IBOutlet") return static_cast<obj::AttributeKind>(197);
  if (name == "IBOutletCollection") return static_cast<obj::AttributeKind>(198);
  if (name == "InitPriority") return static_cast<obj::AttributeKind>(199);
  if (name == "InternalLinkage") return static_cast<obj::AttributeKind>(200);
  if (name == "LTOVisibilityPublic") return static_cast<obj::AttributeKind>(201);
  if (name == "LayoutVersion") return static_cast<obj::AttributeKind>(202);
  if (name == "Leaf") return static_cast<obj::AttributeKind>(203);
  if (name == "LockReturned") return static_cast<obj::AttributeKind>(204);
  if (name == "LocksExcluded") return static_cast<obj::AttributeKind>(205);
  if (name == "M68kInterrupt") return static_cast<obj::AttributeKind>(206);
  if (name == "MIGServerRoutine") return static_cast<obj::AttributeKind>(207);
  if (name == "MSAllocator") return static_cast<obj::AttributeKind>(208);
  if (name == "MSConstexpr") return static_cast<obj::AttributeKind>(209);
  if (name == "MSInheritance") return static_cast<obj::AttributeKind>(210);
  if (name == "MSNoVTable") return static_cast<obj::AttributeKind>(211);
  if (name == "MSP430Interrupt") return static_cast<obj::AttributeKind>(212);
  if (name == "MSStruct") return static_cast<obj::AttributeKind>(213);
  if (name == "MSVtorDisp") return static_cast<obj::AttributeKind>(214);
  if (name == "MaxFieldAlignment") return static_cast<obj::AttributeKind>(215);
  if (name == "MayAlias") return static_cast<obj::AttributeKind>(216);
  if (name == "MaybeUndef") return static_cast<obj::AttributeKind>(217);
  if (name == "MicroMips") return static_cast<obj::AttributeKind>(218);
  if (name == "MinSize") return static_cast<obj::AttributeKind>(219);
  if (name == "MinVectorWidth") return static_cast<obj::AttributeKind>(220);
  if (name == "Mips16") return static_cast<obj::AttributeKind>(221);
  if (name == "MipsInterrupt") return static_cast<obj::AttributeKind>(222);
  if (name == "MipsLongCall") return static_cast<obj::AttributeKind>(223);
  if (name == "MipsShortCall") return static_cast<obj::AttributeKind>(224);
  if (name == "NSConsumesSelf") return static_cast<obj::AttributeKind>(225);
  if (name == "NSErrorDomain") return static_cast<obj::AttributeKind>(226);
  if (name == "NSReturnsAutoreleased") return static_cast<obj::AttributeKind>(227);
  if (name == "NSReturnsNotRetained") return static_cast<obj::AttributeKind>(228);
  if (name == "NVPTXKernel") return static_cast<obj::AttributeKind>(229);
  if (name == "Naked") return static_cast<obj::AttributeKind>(230);
  if (name == "NoAlias") return static_cast<obj::AttributeKind>(231);
  if (name == "NoCommon") return static_cast<obj::AttributeKind>(232);
  if (name == "NoDebug") return static_cast<obj::AttributeKind>(233);
  if (name == "NoDestroy") return static_cast<obj::AttributeKind>(234);
  if (name == "NoDuplicate") return static_cast<obj::AttributeKind>(235);
  if (name == "NoInstrumentFunction") return static_cast<obj::AttributeKind>(236);
  if (name == "NoMicroMips") return static_cast<obj::AttributeKind>(237);
  if (name == "NoMips16") return static_cast<obj::AttributeKind>(238);
  if (name == "NoProfileFunction") return static_cast<obj::AttributeKind>(239);
  if (name == "NoRandomizeLayout") return static_cast<obj::AttributeKind>(240);
  if (name == "NoReturn") return static_cast<obj::AttributeKind>(241);
  if (name == "NoSanitize") return static_cast<obj::AttributeKind>(242);
  if (name == "NoSpeculativeLoadHardening") return static_cast<obj::AttributeKind>(243);
  if (name == "NoSplitStack") return static_cast<obj::AttributeKind>(244);
  if (name == "NoStackProtector") return static_cast<obj::AttributeKind>(245);
  if (name == "NoThreadSafetyAnalysis") return static_cast<obj::AttributeKind>(246);
  if (name == "NoThrow") return static_cast<obj::AttributeKind>(247);
  if (name == "NoUniqueAddress") return static_cast<obj::AttributeKind>(248);
  if (name == "NoUwtable") return static_cast<obj::AttributeKind>(249);
  if (name == "NotTailCalled") return static_cast<obj::AttributeKind>(250);
  if (name == "OMPAllocateDecl") return static_cast<obj::AttributeKind>(251);
  if (name == "OMPCaptureNoInit") return static_cast<obj::AttributeKind>(252);
  if (name == "OMPDeclareTargetDecl") return static_cast<obj::AttributeKind>(253);
  if (name == "OMPDeclareVariant") return static_cast<obj::AttributeKind>(254);
  if (name == "OMPThreadPrivateDecl") return static_cast<obj::AttributeKind>(255);
  if (name == "OSConsumesThis") return static_cast<obj::AttributeKind>(256);
  if (name == "OSReturnsNotRetained") return static_cast<obj::AttributeKind>(257);
  if (name == "OSReturnsRetained") return static_cast<obj::AttributeKind>(258);
  if (name == "OSReturnsRetainedOnNonZero") return static_cast<obj::AttributeKind>(259);
  if (name == "OSReturnsRetainedOnZero") return static_cast<obj::AttributeKind>(260);
  if (name == "ObjCBridge") return static_cast<obj::AttributeKind>(261);
  if (name == "ObjCBridgeMutable") return static_cast<obj::AttributeKind>(262);
  if (name == "ObjCBridgeRelated") return static_cast<obj::AttributeKind>(263);
  if (name == "ObjCException") return static_cast<obj::AttributeKind>(264);
  if (name == "ObjCExplicitProtocolImpl") return static_cast<obj::AttributeKind>(265);
  if (name == "ObjCExternallyRetained") return static_cast<obj::AttributeKind>(266);
  if (name == "ObjCIndependentClass") return static_cast<obj::AttributeKind>(267);
  if (name == "ObjCMethodFamily") return static_cast<obj::AttributeKind>(268);
  if (name == "ObjCNSObject") return static_cast<obj::AttributeKind>(269);
  if (name == "ObjCPreciseLifetime") return static_cast<obj::AttributeKind>(270);
  if (name == "ObjCRequiresPropertyDefs") return static_cast<obj::AttributeKind>(271);
  if (name == "ObjCRequiresSuper") return static_cast<obj::AttributeKind>(272);
  if (name == "ObjCReturnsInnerPointer") return static_cast<obj::AttributeKind>(273);
  if (name == "ObjCRootClass") return static_cast<obj::AttributeKind>(274);
  if (name == "ObjCSubclassingRestricted") return static_cast<obj::AttributeKind>(275);
  if (name == "OpenCLIntelReqdSubGroupSize") return static_cast<obj::AttributeKind>(276);
  if (name == "OpenCLKernel") return static_cast<obj::AttributeKind>(277);
  if (name == "OptimizeNone") return static_cast<obj::AttributeKind>(278);
  if (name == "Override") return static_cast<obj::AttributeKind>(279);
  if (name == "Owner") return static_cast<obj::AttributeKind>(280);
  if (name == "Ownership") return static_cast<obj::AttributeKind>(281);
  if (name == "Packed") return static_cast<obj::AttributeKind>(282);
  if (name == "ParamTypestate") return static_cast<obj::AttributeKind>(283);
  if (name == "PatchableFunctionEntry") return static_cast<obj::AttributeKind>(284);
  if (name == "Pointer") return static_cast<obj::AttributeKind>(285);
  if (name == "PragmaClangBSSSection") return static_cast<obj::AttributeKind>(286);
  if (name == "PragmaClangDataSection") return static_cast<obj::AttributeKind>(287);
  if (name == "PragmaClangRelroSection") return static_cast<obj::AttributeKind>(288);
  if (name == "PragmaClangRodataSection") return static_cast<obj::AttributeKind>(289);
  if (name == "PragmaClangTextSection") return static_cast<obj::AttributeKind>(290);
  if (name == "PreferredName") return static_cast<obj::AttributeKind>(291);
  if (name == "PreferredType") return static_cast<obj::AttributeKind>(292);
  if (name == "PtGuardedBy") return static_cast<obj::AttributeKind>(293);
  if (name == "PtGuardedVar") return static_cast<obj::AttributeKind>(294);
  if (name == "Pure") return static_cast<obj::AttributeKind>(295);
  if (name == "RISCVInterrupt") return static_cast<obj::AttributeKind>(296);
  if (name == "RandomizeLayout") return static_cast<obj::AttributeKind>(297);
  if (name == "ReadOnlyPlacement") return static_cast<obj::AttributeKind>(298);
  if (name == "Reinitializes") return static_cast<obj::AttributeKind>(299);
  if (name == "ReleaseCapability") return static_cast<obj::AttributeKind>(300);
  if (name == "ReqdWorkGroupSize") return static_cast<obj::AttributeKind>(301);
  if (name == "RequiresCapability") return static_cast<obj::AttributeKind>(302);
  if (name == "Restrict") return static_cast<obj::AttributeKind>(303);
  if (name == "Retain") return static_cast<obj::AttributeKind>(304);
  if (name == "ReturnTypestate") return static_cast<obj::AttributeKind>(305);
  if (name == "ReturnsNonNull") return static_cast<obj::AttributeKind>(306);
  if (name == "ReturnsTwice") return static_cast<obj::AttributeKind>(307);
  if (name == "SYCLKernel") return static_cast<obj::AttributeKind>(308);
  if (name == "SYCLSpecialClass") return static_cast<obj::AttributeKind>(309);
  if (name == "ScopedLockable") return static_cast<obj::AttributeKind>(310);
  if (name == "Section") return static_cast<obj::AttributeKind>(311);
  if (name == "SelectAny") return static_cast<obj::AttributeKind>(312);
  if (name == "Sentinel") return static_cast<obj::AttributeKind>(313);
  if (name == "SetTypestate") return static_cast<obj::AttributeKind>(314);
  if (name == "SharedTrylockFunction") return static_cast<obj::AttributeKind>(315);
  if (name == "SpeculativeLoadHardening") return static_cast<obj::AttributeKind>(316);
  if (name == "StandaloneDebug") return static_cast<obj::AttributeKind>(317);
  if (name == "StrictFP") return static_cast<obj::AttributeKind>(318);
  if (name == "StrictGuardStackCheck") return static_cast<obj::AttributeKind>(319);
  if (name == "SwiftAsync") return static_cast<obj::AttributeKind>(320);
  if (name == "SwiftAsyncError") return static_cast<obj::AttributeKind>(321);
  if (name == "SwiftAsyncName") return static_cast<obj::AttributeKind>(322);
  if (name == "SwiftAttr") return static_cast<obj::AttributeKind>(323);
  if (name == "SwiftBridge") return static_cast<obj::AttributeKind>(324);
  if (name == "SwiftBridgedTypedef") return static_cast<obj::AttributeKind>(325);
  if (name == "SwiftError") return static_cast<obj::AttributeKind>(326);
  if (name == "SwiftImportAsNonGeneric") return static_cast<obj::AttributeKind>(327);
  if (name == "SwiftImportPropertyAsAccessors") return static_cast<obj::AttributeKind>(328);
  if (name == "SwiftName") return static_cast<obj::AttributeKind>(329);
  if (name == "SwiftNewType") return static_cast<obj::AttributeKind>(330);
  if (name == "SwiftPrivate") return static_cast<obj::AttributeKind>(331);
  if (name == "TLSModel") return static_cast<obj::AttributeKind>(332);
  if (name == "Target") return static_cast<obj::AttributeKind>(333);
  if (name == "TargetClones") return static_cast<obj::AttributeKind>(334);
  if (name == "TargetVersion") return static_cast<obj::AttributeKind>(335);
  if (name == "TestTypestate") return static_cast<obj::AttributeKind>(336);
  if (name == "TransparentUnion") return static_cast<obj::AttributeKind>(337);
  if (name == "TrivialABI") return static_cast<obj::AttributeKind>(338);
  if (name == "TryAcquireCapability") return static_cast<obj::AttributeKind>(339);
  if (name == "TypeTagForDatatype") return static_cast<obj::AttributeKind>(340);
  if (name == "TypeVisibility") return static_cast<obj::AttributeKind>(341);
  if (name == "Unavailable") return static_cast<obj::AttributeKind>(342);
  if (name == "Uninitialized") return static_cast<obj::AttributeKind>(343);
  if (name == "UnsafeBufferUsage") return static_cast<obj::AttributeKind>(344);
  if (name == "Unused") return static_cast<obj::AttributeKind>(345);
  if (name == "Used") return static_cast<obj::AttributeKind>(346);
  if (name == "UsingIfExists") return static_cast<obj::AttributeKind>(347);
  if (name == "Uuid") return static_cast<obj::AttributeKind>(348);
  if (name == "VecReturn") return static_cast<obj::AttributeKind>(349);
  if (name == "VecTypeHint") return static_cast<obj::AttributeKind>(350);
  if (name == "Visibility") return static_cast<obj::AttributeKind>(351);
  if (name == "WarnUnused") return static_cast<obj::AttributeKind>(352);
  if (name == "WarnUnusedResult") return static_cast<obj::AttributeKind>(353);
  if (name == "Weak") return static_cast<obj::AttributeKind>(354);
  if (name == "WeakImport") return static_cast<obj::AttributeKind>(355);
  if (name == "WeakRef") return static_cast<obj::AttributeKind>(356);
  if (name == "WebAssemblyExportName") return static_cast<obj::AttributeKind>(357);
  if (name == "WebAssemblyImportModule") return static_cast<obj::AttributeKind>(358);
  if (name == "WebAssemblyImportName") return static_cast<obj::AttributeKind>(359);
  if (name == "WorkGroupSizeHint") return static_cast<obj::AttributeKind>(360);
  if (name == "X86ForceAlignArgPointer") return static_cast<obj::AttributeKind>(361);
  if (name == "XRayInstrument") return static_cast<obj::AttributeKind>(362);
  if (name == "XRayLogArgs") return static_cast<obj::AttributeKind>(363);
  if (name == "ZeroCallUsedRegs") return static_cast<obj::AttributeKind>(364);
  if (name == "AbiTag") return static_cast<obj::AttributeKind>(365);
  if (name == "Alias") return static_cast<obj::AttributeKind>(366);
  if (name == "AlignValue") return static_cast<obj::AttributeKind>(367);
  if (name == "BuiltinAlias") return static_cast<obj::AttributeKind>(368);
  if (name == "CalledOnce") return static_cast<obj::AttributeKind>(369);
  if (name == "IFunc") return static_cast<obj::AttributeKind>(370);
  if (name == "InitSeg") return static_cast<obj::AttributeKind>(371);
  if (name == "LoaderUninitialized") return static_cast<obj::AttributeKind>(372);
  if (name == "LoopHint") return static_cast<obj::AttributeKind>(373);
  if (name == "Mode") return static_cast<obj::AttributeKind>(374);
  if (name == "NoBuiltin") return static_cast<obj::AttributeKind>(375);
  if (name == "NoEscape") return static_cast<obj::AttributeKind>(376);
  if (name == "OMPCaptureKind") return static_cast<obj::AttributeKind>(377);
  if (name == "OMPDeclareSimdDecl") return static_cast<obj::AttributeKind>(378);
  if (name == "OMPReferencedVar") return static_cast<obj::AttributeKind>(379);
  if (name == "ObjCBoxable") return static_cast<obj::AttributeKind>(380);
  if (name == "ObjCClassStub") return static_cast<obj::AttributeKind>(381);
  if (name == "ObjCDesignatedInitializer") return static_cast<obj::AttributeKind>(382);
  if (name == "ObjCDirect") return static_cast<obj::AttributeKind>(383);
  if (name == "ObjCDirectMembers") return static_cast<obj::AttributeKind>(384);
  if (name == "ObjCNonLazyClass") return static_cast<obj::AttributeKind>(385);
  if (name == "ObjCNonRuntimeProtocol") return static_cast<obj::AttributeKind>(386);
  if (name == "ObjCRuntimeName") return static_cast<obj::AttributeKind>(387);
  if (name == "ObjCRuntimeVisible") return static_cast<obj::AttributeKind>(388);
  if (name == "OpenCLAccess") return static_cast<obj::AttributeKind>(389);
  if (name == "Overloadable") return static_cast<obj::AttributeKind>(390);
  if (name == "RenderScriptKernel") return static_cast<obj::AttributeKind>(391);
  if (name == "SwiftObjCMembers") return static_cast<obj::AttributeKind>(392);
  if (name == "SwiftVersionedAddition") return static_cast<obj::AttributeKind>(393);
  if (name == "SwiftVersionedRemoval") return static_cast<obj::AttributeKind>(394);
  if (name == "Thread") return static_cast<obj::AttributeKind>(395);
  if (name == "FirstAttr") return static_cast<obj::AttributeKind>(396);
  if (name == "LastAttr") return static_cast<obj::AttributeKind>(397);
  if (name == "FirstTypeAttr") return static_cast<obj::AttributeKind>(398);
  if (name == "LastTypeAttr") return static_cast<obj::AttributeKind>(399);
  if (name == "FirstStmtAttr") return static_cast<obj::AttributeKind>(400);
  if (name == "LastStmtAttr") return static_cast<obj::AttributeKind>(401);
  if (name == "FirstDeclOrStmtAttr") return static_cast<obj::AttributeKind>(402);
  if (name == "LastDeclOrStmtAttr") return static_cast<obj::AttributeKind>(403);
  if (name == "FirstInheritableAttr") return static_cast<obj::AttributeKind>(404);
  if (name == "LastInheritableAttr") return static_cast<obj::AttributeKind>(405);
  if (name == "FirstDeclOrTypeAttr") return static_cast<obj::AttributeKind>(406);
  if (name == "LastDeclOrTypeAttr") return static_cast<obj::AttributeKind>(407);
  if (name == "FirstInheritableParamAttr") return static_cast<obj::AttributeKind>(408);
  if (name == "LastInheritableParamAttr") return static_cast<obj::AttributeKind>(409);
  if (name == "FirstParameterABIAttr") return static_cast<obj::AttributeKind>(410);
  if (name == "LastParameterABIAttr") return static_cast<obj::AttributeKind>(411);
  if (name == "FirstHLSLAnnotationAttr") return static_cast<obj::AttributeKind>(412);
  if (name == "LastHLSLAnnotationAttr") return static_cast<obj::AttributeKind>(413);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::FormatAttrKind enumValue<obj::FormatAttrKind>(std::string_view name) {
  if (name == "printf") return static_cast<obj::FormatAttrKind>(0);
  if (name == "scanf") return static_cast<obj::FormatAttrKind>(1);
  if (name == "strftime") return static_cast<obj::FormatAttrKind>(2);
  if (name == "gnu_printf") return static_cast<obj::FormatAttrKind>(3);
  if (name == "gnu_scanf") return static_cast<obj::FormatAttrKind>(4);
  if (name == "gnu_strftime") return static_cast<obj::FormatAttrKind>(5);
  if (name == "strfmon") return static_cast<obj::FormatAttrKind>(6);
  if (name == "ms_printf") return static_cast<obj::FormatAttrKind>(7);
  if (name == "ms_scanf") return static_cast<obj::FormatAttrKind>(8);
  if (name == "ms_strftime") return static_cast<obj::FormatAttrKind>(9);
  if (name == "NSString") return static_cast<obj::FormatAttrKind>(10);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::VisibilityType enumValue<obj::VisibilityType>(std::string_view name) {
  if (name == "Default") return static_cast<obj::VisibilityType>(0);
  if (name == "Hidden") return static_cast<obj::VisibilityType>(1);
  if (name == "Protected") return static_cast<obj::VisibilityType>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ExplicitSpecKind enumValue<obj::ExplicitSpecKind>(std::string_view name) {
  if (name == "ResolvedFalse") return static_cast<obj::ExplicitSpecKind>(0);
  if (name == "ResolvedTrue") return static_cast<obj::ExplicitSpecKind>(1);
  if (name == "Unresolved") return static_cast<obj::ExplicitSpecKind>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::InitializationStyle enumValue<obj::InitializationStyle>(std::string_view name) {
  if (name == "CINIT") return static_cast<obj::InitializationStyle>(0);
  if (name == "CALL_INIT") return static_cast<obj::InitializationStyle>(1);
  if (name == "LIST_INIT") return static_cast<obj::InitializationStyle>(2);
  if (name == "ParenListInit") return static_cast<obj::InitializationStyle>(3);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::LanguageId enumValue<obj::LanguageId>(std::string_view name) {
  if (name == "C") return static_cast<obj::LanguageId>(0);
  if (name == "CXX") return static_cast<obj::LanguageId>(1);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::Linkage enumValue<obj::Linkage>(std::string_view name) {
  if (name == "Invalid") return static_cast<obj::Linkage>(0);
  if (name == "None") return static_cast<obj::Linkage>(1);
  if (name == "Internal") return static_cast<obj::Linkage>(2);
  if (name == "UniqueExternal") return static_cast<obj::Linkage>(3);
  if (name == "VisibleNone") return static_cast<obj::Linkage>(4);
  if (name == "Module") return static_cast<obj::Linkage>(5);
  if (name == "External") return static_cast<obj::Linkage>(6);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::NameKind enumValue<obj::NameKind>(std::string_view name) {
  if (name == "IDENTIFIER") return static_cast<obj::NameKind>(0);
  if (name == "OBJ_C_ZERO_ARG_SELECTOR") return static_cast<obj::NameKind>(1);
  if (name == "OBJ_C_ONE_ARG_SELECTOR") return static_cast<obj::NameKind>(2);
  if (name == "OBJ_C_MULTI_ARG_SELECTOR") return static_cast<obj::NameKind>(3);
  if (name == "CXX_CONSTRUCTOR_NAME") return static_cast<obj::NameKind>(4);
  if (name == "CXX_DESTRUCTOR_NAME") return static_cast<obj::NameKind>(5);
  if (name == "CXX_CONVERSION_FUNCTION_NAME") return static_cast<obj::NameKind>(6);
  if (name == "CXX_DEDUCTION_GUIDE_NAME") return static_cast<obj::NameKind>(7);
  if (name == "CXX_OPERATOR_NAME") return static_cast<obj::NameKind>(8);
  if (name == "CXX_LITERAL_OPERATOR_NAME") return static_cast<obj::NameKind>(9);
  if (name == "CXX_USING_DIRECTIVE") return static_cast<obj::NameKind>(10);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::StorageClass enumValue<obj::StorageClass>(std::string_view name) {
  if (name == "None") return static_cast<obj::StorageClass>(0);
  if (name == "Extern") return static_cast<obj::StorageClass>(1);
  if (name == "Static") return static_cast<obj::StorageClass>(2);
  if (name == "PrivateExtern") return static_cast<obj::StorageClass>(3);
  if (name == "Auto") return static_cast<obj::StorageClass>(4);
  if (name == "Register") return static_cast<obj::StorageClass>(5);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TemplateKind enumValue<obj::TemplateKind>(std::string_view name) {
  if (name == "NON_TEMPLATE") return static_cast<obj::TemplateKind>(0);
  if (name == "FUNCTION_TEMPLATE") return static_cast<obj::TemplateKind>(1);
  if (name == "MEMBER_SPECIALIZATION") return static_cast<obj::TemplateKind>(2);
  if (name == "FUNCTION_TEMPLATE_SPECIALIZATION") return static_cast<obj::TemplateKind>(3);
  if (name == "DEPENDENT_FUNCTION_TEMPLATE_SPECIALIZATION") return static_cast<obj::TemplateKind>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TemplateSpecializationKind enumValue<obj::TemplateSpecializationKind>(std::string_view name) {
  if (name == "Undeclared") return static_cast<obj::TemplateSpecializationKind>(0);
  if (name == "ImplicitInstantiation") return static_cast<obj::TemplateSpecializationKind>(1);
  if (name == "ExplicitSpecialization") return static_cast<obj::TemplateSpecializationKind>(2);
  if (name == "ExplicitInstantiationDeclaration") return static_cast<obj::TemplateSpecializationKind>(3);
  if (name == "ExplicitInstantiationDefinition") return static_cast<obj::TemplateSpecializationKind>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::Visibility enumValue<obj::Visibility>(std::string_view name) {
  if (name == "Hidden") return static_cast<obj::Visibility>(0);
  if (name == "Protected") return static_cast<obj::Visibility>(1);
  if (name == "Default") return static_cast<obj::Visibility>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::BinaryOperatorKind enumValue<obj::BinaryOperatorKind>(std::string_view name) {
  if (name == "PtrMemD") return static_cast<obj::BinaryOperatorKind>(0);
  if (name == "PtrMemI") return static_cast<obj::BinaryOperatorKind>(1);
  if (name == "Mul") return static_cast<obj::BinaryOperatorKind>(2);
  if (name == "Div") return static_cast<obj::BinaryOperatorKind>(3);
  if (name == "Rem") return static_cast<obj::BinaryOperatorKind>(4);
  if (name == "Add") return static_cast<obj::BinaryOperatorKind>(5);
  if (name == "Sub") return static_cast<obj::BinaryOperatorKind>(6);
  if (name == "Shl") return static_cast<obj::BinaryOperatorKind>(7);
  if (name == "Shr") return static_cast<obj::BinaryOperatorKind>(8);
  if (name == "Cmp") return static_cast<obj::BinaryOperatorKind>(9);
  if (name == "LT") return static_cast<obj::BinaryOperatorKind>(10);
  if (name == "GT") return static_cast<obj::BinaryOperatorKind>(11);
  if (name == "LE") return static_cast<obj::BinaryOperatorKind>(12);
  if (name == "GE") return static_cast<obj::BinaryOperatorKind>(13);
  if (name == "EQ") return static_cast<obj::BinaryOperatorKind>(14);
  if (name == "NE") return static_cast<obj::BinaryOperatorKind>(15);
  if (name == "And") return static_cast<obj::BinaryOperatorKind>(16);
  if (name == "Xor") return static_cast<obj::BinaryOperatorKind>(17);
  if (name == "Or") return static_cast<obj::BinaryOperatorKind>(18);
  if (name == "LAnd") return static_cast<obj::BinaryOperatorKind>(19);
  if (name == "LOr") return static_cast<obj::BinaryOperatorKind>(20);
  if (name == "Assign") return static_cast<obj::BinaryOperatorKind>(21);
  if (name == "MulAssign") return static_cast<obj::BinaryOperatorKind>(22);
  if (name == "DivAssign") return static_cast<obj::BinaryOperatorKind>(23);
  if (name == "RemAssign") return static_cast<obj::BinaryOperatorKind>(24);
  if (name == "AddAssign") return static_cast<obj::BinaryOperatorKind>(25);
  if (name == "SubAssign") return static_cast<obj::BinaryOperatorKind>(26);
  if (name == "ShlAssign") return static_cast<obj::BinaryOperatorKind>(27);
  if (name == "ShrAssign") return static_cast<obj::BinaryOperatorKind>(28);
  if (name == "AndAssign") return static_cast<obj::BinaryOperatorKind>(29);
  if (name == "XorAssign") return static_cast<obj::BinaryOperatorKind>(30);
  if (name == "OrAssign") return static_cast<obj::BinaryOperatorKind>(31);
  if (name == "Comma") return static_cast<obj::BinaryOperatorKind>(32);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::CharacterKind enumValue<obj::CharacterKind>(std::string_view name) {
  if (name == "ASCII") return static_cast<obj::CharacterKind>(0);
  if (name == "WIDE") return static_cast<obj::CharacterKind>(1);
  if (name == "UTF8") return static_cast<obj::CharacterKind>(2);
  if (name == "UTF16") return static_cast<obj::CharacterKind>(3);
  if (name == "UTF32") return static_cast<obj::CharacterKind>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ConstructionKind enumValue<obj::ConstructionKind>(std::string_view name) {
  if (name == "Complete") return static_cast<obj::ConstructionKind>(0);
  if (name == "NonVirtualBase") return static_cast<obj::ConstructionKind>(1);
  if (name == "VirtualBase") return static_cast<obj::ConstructionKind>(2);
  if (name == "Delegating") return static_cast<obj::ConstructionKind>(3);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::LambdaCaptureDefault enumValue<obj::LambdaCaptureDefault>(std::string_view name) {
  if (name == "None") return static_cast<obj::LambdaCaptureDefault>(0);
  if (name == "ByCopy") return static_cast<obj::LambdaCaptureDefault>(1);
  if (name == "ByRef") return static_cast<obj::LambdaCaptureDefault>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::LambdaCaptureKind enumValue<obj::LambdaCaptureKind>(std::string_view name) {
  if (name == "This") return static_cast<obj::LambdaCaptureKind>(0);
  if (name == "StarThis") return static_cast<obj::LambdaCaptureKind>(1);
  if (name == "ByCopy") return static_cast<obj::LambdaCaptureKind>(2);
  if (name == "ByRef") return static_cast<obj::LambdaCaptureKind>(3);
  if (name == "VLAType") return static_cast<obj::LambdaCaptureKind>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::NewInitStyle enumValue<obj::NewInitStyle>(std::string_view name) {
  if (name == "NO_INIT") return static_cast<obj::NewInitStyle>(0);
  if (name == "CALL_INIT") return static_cast<obj::NewInitStyle>(1);
  if (name == "LIST_INIT") return static_cast<obj::NewInitStyle>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ObjectKind enumValue<obj::ObjectKind>(std::string_view name) {
  if (name == "ORDINARY") return static_cast<obj::ObjectKind>(0);
  if (name == "BIT_FIELD") return static_cast<obj::ObjectKind>(1);
  if (name == "OBJ_C_PROPERTY") return static_cast<obj::ObjectKind>(2);
  if (name == "OBJ_C_SUBSCRIPT") return static_cast<obj::ObjectKind>(3);
  if (name == "VECTOR_COMPONENT") return static_cast<obj::ObjectKind>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::PredefinedIdType enumValue<obj::PredefinedIdType>(std::string_view name) {
  if (name == "Func") return static_cast<obj::PredefinedIdType>(0);
  if (name == "Function") return static_cast<obj::PredefinedIdType>(1);
  if (name == "LFunction") return static_cast<obj::PredefinedIdType>(2);
  if (name == "FuncDName") return static_cast<obj::PredefinedIdType>(3);
  if (name == "FuncSig") return static_cast<obj::PredefinedIdType>(4);
  if (name == "LFuncSig") return static_cast<obj::PredefinedIdType>(5);
  if (name == "PrettyFunction") return static_cast<obj::PredefinedIdType>(6);
  if (name == "PrettyFunctionNoVirtual") return static_cast<obj::PredefinedIdType>(7);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::StringKind enumValue<obj::StringKind>(std::string_view name) {
  if (name == "ORDINARY") return static_cast<obj::StringKind>(0);
  if (name == "WIDE") return static_cast<obj::StringKind>(1);
  if (name == "UTF8") return static_cast<obj::StringKind>(2);
  if (name == "UTF16") return static_cast<obj::StringKind>(3);
  if (name == "UTF32") return static_cast<obj::StringKind>(4);
  if (name == "UNEVALUATED") return static_cast<obj::StringKind>(5);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::UnaryOperatorKind enumValue<obj::UnaryOperatorKind>(std::string_view name) {
  if (name == "PostInc") return static_cast<obj::UnaryOperatorKind>(0);
  if (name == "PostDec") return static_cast<obj::UnaryOperatorKind>(1);
  if (name == "PreInc") return static_cast<obj::UnaryOperatorKind>(2);
  if (name == "PreDec") return static_cast<obj::UnaryOperatorKind>(3);
  if (name == "AddrOf") return static_cast<obj::UnaryOperatorKind>(4);
  if (name == "Deref") return static_cast<obj::UnaryOperatorKind>(5);
  if (name == "Plus") return static_cast<obj::UnaryOperatorKind>(6);
  if (name == "Minus") return static_cast<obj::UnaryOperatorKind>(7);
  if (name == "Not") return static_cast<obj::UnaryOperatorKind>(8);
  if (name == "LNot") return static_cast<obj::UnaryOperatorKind>(9);
  if (name == "Real") return static_cast<obj::UnaryOperatorKind>(10);
  if (name == "Imag") return static_cast<obj::UnaryOperatorKind>(11);
  if (name == "Extension") return static_cast<obj::UnaryOperatorKind>(12);
  if (name == "Coawait") return static_cast<obj::UnaryOperatorKind>(13);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::UnaryOperatorPosition enumValue<obj::UnaryOperatorPosition>(std::string_view name) {
  if (name == "PREFIX") return static_cast<obj::UnaryOperatorPosition>(0);
  if (name == "POSTFIX") return static_cast<obj::UnaryOperatorPosition>(1);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ValueKind enumValue<obj::ValueKind>(std::string_view name) {
  if (name == "R_VALUE") return static_cast<obj::ValueKind>(0);
  if (name == "L_VALUE") return static_cast<obj::ValueKind>(1);
  if (name == "X_VALUE") return static_cast<obj::ValueKind>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::AddressSpaceQualifierV2 enumValue<obj::AddressSpaceQualifierV2>(std::string_view name) {
  if (name == "NONE") return static_cast<obj::AddressSpaceQualifierV2>(0);
  if (name == "GLOBAL") return static_cast<obj::AddressSpaceQualifierV2>(1);
  if (name == "LOCAL") return static_cast<obj::AddressSpaceQualifierV2>(2);
  if (name == "CONSTANT") return static_cast<obj::AddressSpaceQualifierV2>(3);
  if (name == "GENERIC") return static_cast<obj::AddressSpaceQualifierV2>(4);
  if (name == "DEFAULT") return static_cast<obj::AddressSpaceQualifierV2>(5);
  if (name == "PRIVATE") return static_cast<obj::AddressSpaceQualifierV2>(6);
  if (name == "CUDA_CONSTANT") return static_cast<obj::AddressSpaceQualifierV2>(7);
  if (name == "CUDA_DEVICE") return static_cast<obj::AddressSpaceQualifierV2>(8);
  if (name == "CUDA_SHARED") return static_cast<obj::AddressSpaceQualifierV2>(9);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ArraySizeModifier enumValue<obj::ArraySizeModifier>(std::string_view name) {
  if (name == "Normal") return static_cast<obj::ArraySizeModifier>(0);
  if (name == "Static") return static_cast<obj::ArraySizeModifier>(1);
  if (name == "Star") return static_cast<obj::ArraySizeModifier>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::BuiltinKind enumValue<obj::BuiltinKind>(std::string_view name) {
  if (name == "OCLImage1dRO") return static_cast<obj::BuiltinKind>(0);
  if (name == "OCLImage1dArrayRO") return static_cast<obj::BuiltinKind>(1);
  if (name == "OCLImage1dBufferRO") return static_cast<obj::BuiltinKind>(2);
  if (name == "OCLImage2dRO") return static_cast<obj::BuiltinKind>(3);
  if (name == "OCLImage2dArrayRO") return static_cast<obj::BuiltinKind>(4);
  if (name == "OCLImage2dDepthRO") return static_cast<obj::BuiltinKind>(5);
  if (name == "OCLImage2dArrayDepthRO") return static_cast<obj::BuiltinKind>(6);
  if (name == "OCLImage2dMSAARO") return static_cast<obj::BuiltinKind>(7);
  if (name == "OCLImage2dArrayMSAARO") return static_cast<obj::BuiltinKind>(8);
  if (name == "OCLImage2dMSAADepthRO") return static_cast<obj::BuiltinKind>(9);
  if (name == "OCLImage2dArrayMSAADepthRO") return static_cast<obj::BuiltinKind>(10);
  if (name == "OCLImage3dRO") return static_cast<obj::BuiltinKind>(11);
  if (name == "OCLImage1dWO") return static_cast<obj::BuiltinKind>(12);
  if (name == "OCLImage1dArrayWO") return static_cast<obj::BuiltinKind>(13);
  if (name == "OCLImage1dBufferWO") return static_cast<obj::BuiltinKind>(14);
  if (name == "OCLImage2dWO") return static_cast<obj::BuiltinKind>(15);
  if (name == "OCLImage2dArrayWO") return static_cast<obj::BuiltinKind>(16);
  if (name == "OCLImage2dDepthWO") return static_cast<obj::BuiltinKind>(17);
  if (name == "OCLImage2dArrayDepthWO") return static_cast<obj::BuiltinKind>(18);
  if (name == "OCLImage2dMSAAWO") return static_cast<obj::BuiltinKind>(19);
  if (name == "OCLImage2dArrayMSAAWO") return static_cast<obj::BuiltinKind>(20);
  if (name == "OCLImage2dMSAADepthWO") return static_cast<obj::BuiltinKind>(21);
  if (name == "OCLImage2dArrayMSAADepthWO") return static_cast<obj::BuiltinKind>(22);
  if (name == "OCLImage3dWO") return static_cast<obj::BuiltinKind>(23);
  if (name == "OCLImage1dRW") return static_cast<obj::BuiltinKind>(24);
  if (name == "OCLImage1dArrayRW") return static_cast<obj::BuiltinKind>(25);
  if (name == "OCLImage1dBufferRW") return static_cast<obj::BuiltinKind>(26);
  if (name == "OCLImage2dRW") return static_cast<obj::BuiltinKind>(27);
  if (name == "OCLImage2dArrayRW") return static_cast<obj::BuiltinKind>(28);
  if (name == "OCLImage2dDepthRW") return static_cast<obj::BuiltinKind>(29);
  if (name == "OCLImage2dArrayDepthRW") return static_cast<obj::BuiltinKind>(30);
  if (name == "OCLImage2dMSAARW") return static_cast<obj::BuiltinKind>(31);
  if (name == "OCLImage2dArrayMSAARW") return static_cast<obj::BuiltinKind>(32);
  if (name == "OCLImage2dMSAADepthRW") return static_cast<obj::BuiltinKind>(33);
  if (name == "OCLImage2dArrayMSAADepthRW") return static_cast<obj::BuiltinKind>(34);
  if (name == "OCLImage3dRW") return static_cast<obj::BuiltinKind>(35);
  if (name == "OCLIntelSubgroupAVCMcePayload") return static_cast<obj::BuiltinKind>(36);
  if (name == "OCLIntelSubgroupAVCImePayload") return static_cast<obj::BuiltinKind>(37);
  if (name == "OCLIntelSubgroupAVCRefPayload") return static_cast<obj::BuiltinKind>(38);
  if (name == "OCLIntelSubgroupAVCSicPayload") return static_cast<obj::BuiltinKind>(39);
  if (name == "OCLIntelSubgroupAVCMceResult") return static_cast<obj::BuiltinKind>(40);
  if (name == "OCLIntelSubgroupAVCImeResult") return static_cast<obj::BuiltinKind>(41);
  if (name == "OCLIntelSubgroupAVCRefResult") return static_cast<obj::BuiltinKind>(42);
  if (name == "OCLIntelSubgroupAVCSicResult") return static_cast<obj::BuiltinKind>(43);
  if (name == "OCLIntelSubgroupAVCImeResultSingleRefStreamout") return static_cast<obj::BuiltinKind>(44);
  if (name == "OCLIntelSubgroupAVCImeResultDualRefStreamout") return static_cast<obj::BuiltinKind>(45);
  if (name == "OCLIntelSubgroupAVCImeSingleRefStreamin") return static_cast<obj::BuiltinKind>(46);
  if (name == "OCLIntelSubgroupAVCImeDualRefStreamin") return static_cast<obj::BuiltinKind>(47);
  if (name == "SveInt8") return static_cast<obj::BuiltinKind>(48);
  if (name == "SveInt16") return static_cast<obj::BuiltinKind>(49);
  if (name == "SveInt32") return static_cast<obj::BuiltinKind>(50);
  if (name == "SveInt64") return static_cast<obj::BuiltinKind>(51);
  if (name == "SveUint8") return static_cast<obj::BuiltinKind>(52);
  if (name == "SveUint16") return static_cast<obj::BuiltinKind>(53);
  if (name == "SveUint32") return static_cast<obj::BuiltinKind>(54);
  if (name == "SveUint64") return static_cast<obj::BuiltinKind>(55);
  if (name == "SveFloat16") return static_cast<obj::BuiltinKind>(56);
  if (name == "SveFloat32") return static_cast<obj::BuiltinKind>(57);
  if (name == "SveFloat64") return static_cast<obj::BuiltinKind>(58);
  if (name == "SveBFloat16") return static_cast<obj::BuiltinKind>(59);
  if (name == "SveInt8x2") return static_cast<obj::BuiltinKind>(60);
  if (name == "SveInt16x2") return static_cast<obj::BuiltinKind>(61);
  if (name == "SveInt32x2") return static_cast<obj::BuiltinKind>(62);
  if (name == "SveInt64x2") return static_cast<obj::BuiltinKind>(63);
  if (name == "SveUint8x2") return static_cast<obj::BuiltinKind>(64);
  if (name == "SveUint16x2") return static_cast<obj::BuiltinKind>(65);
  if (name == "SveUint32x2") return static_cast<obj::BuiltinKind>(66);
  if (name == "SveUint64x2") return static_cast<obj::BuiltinKind>(67);
  if (name == "SveFloat16x2") return static_cast<obj::BuiltinKind>(68);
  if (name == "SveFloat32x2") return static_cast<obj::BuiltinKind>(69);
  if (name == "SveFloat64x2") return static_cast<obj::BuiltinKind>(70);
  if (name == "SveBFloat16x2") return static_cast<obj::BuiltinKind>(71);
  if (name == "SveInt8x3") return static_cast<obj::BuiltinKind>(72);
  if (name == "SveInt16x3") return static_cast<obj::BuiltinKind>(73);
  if (name == "SveInt32x3") return static_cast<obj::BuiltinKind>(74);
  if (name == "SveInt64x3") return static_cast<obj::BuiltinKind>(75);
  if (name == "SveUint8x3") return static_cast<obj::BuiltinKind>(76);
  if (name == "SveUint16x3") return static_cast<obj::BuiltinKind>(77);
  if (name == "SveUint32x3") return static_cast<obj::BuiltinKind>(78);
  if (name == "SveUint64x3") return static_cast<obj::BuiltinKind>(79);
  if (name == "SveFloat16x3") return static_cast<obj::BuiltinKind>(80);
  if (name == "SveFloat32x3") return static_cast<obj::BuiltinKind>(81);
  if (name == "SveFloat64x3") return static_cast<obj::BuiltinKind>(82);
  if (name == "SveBFloat16x3") return static_cast<obj::BuiltinKind>(83);
  if (name == "SveInt8x4") return static_cast<obj::BuiltinKind>(84);
  if (name == "SveInt16x4") return static_cast<obj::BuiltinKind>(85);
  if (name == "SveInt32x4") return static_cast<obj::BuiltinKind>(86);
  if (name == "SveInt64x4") return static_cast<obj::BuiltinKind>(87);
  if (name == "SveUint8x4") return static_cast<obj::BuiltinKind>(88);
  if (name == "SveUint16x4") return static_cast<obj::BuiltinKind>(89);
  if (name == "SveUint32x4") return static_cast<obj::BuiltinKind>(90);
  if (name == "SveUint64x4") return static_cast<obj::BuiltinKind>(91);
  if (name == "SveFloat16x4") return static_cast<obj::BuiltinKind>(92);
  if (name == "SveFloat32x4") return static_cast<obj::BuiltinKind>(93);
  if (name == "SveFloat64x4") return static_cast<obj::BuiltinKind>(94);
  if (name == "SveBFloat16x4") return static_cast<obj::BuiltinKind>(95);
  if (name == "SveBool") return static_cast<obj::BuiltinKind>(96);
  if (name == "VectorQuad") return static_cast<obj::BuiltinKind>(97);
  if (name == "VectorPair") return static_cast<obj::BuiltinKind>(98);
  if (name == "RvvInt8mf8") return static_cast<obj::BuiltinKind>(99);
  if (name == "RvvInt8mf4") return static_cast<obj::BuiltinKind>(100);
  if (name == "RvvInt8mf2") return static_cast<obj::BuiltinKind>(101);
  if (name == "RvvInt8m1") return static_cast<obj::BuiltinKind>(102);
  if (name == "RvvInt8m2") return static_cast<obj::BuiltinKind>(103);
  if (name == "RvvInt8m4") return static_cast<obj::BuiltinKind>(104);
  if (name == "RvvInt8m8") return static_cast<obj::BuiltinKind>(105);
  if (name == "RvvUint8mf8") return static_cast<obj::BuiltinKind>(106);
  if (name == "RvvUint8mf4") return static_cast<obj::BuiltinKind>(107);
  if (name == "RvvUint8mf2") return static_cast<obj::BuiltinKind>(108);
  if (name == "RvvUint8m1") return static_cast<obj::BuiltinKind>(109);
  if (name == "RvvUint8m2") return static_cast<obj::BuiltinKind>(110);
  if (name == "RvvUint8m4") return static_cast<obj::BuiltinKind>(111);
  if (name == "RvvUint8m8") return static_cast<obj::BuiltinKind>(112);
  if (name == "RvvInt16mf4") return static_cast<obj::BuiltinKind>(113);
  if (name == "RvvInt16mf2") return static_cast<obj::BuiltinKind>(114);
  if (name == "RvvInt16m1") return static_cast<obj::BuiltinKind>(115);
  if (name == "RvvInt16m2") return static_cast<obj::BuiltinKind>(116);
  if (name == "RvvInt16m4") return static_cast<obj::BuiltinKind>(117);
  if (name == "RvvInt16m8") return static_cast<obj::BuiltinKind>(118);
  if (name == "RvvUint16mf4") return static_cast<obj::BuiltinKind>(119);
  if (name == "RvvUint16mf2") return static_cast<obj::BuiltinKind>(120);
  if (name == "RvvUint16m1") return static_cast<obj::BuiltinKind>(121);
  if (name == "RvvUint16m2") return static_cast<obj::BuiltinKind>(122);
  if (name == "RvvUint16m4") return static_cast<obj::BuiltinKind>(123);
  if (name == "RvvUint16m8") return static_cast<obj::BuiltinKind>(124);
  if (name == "RvvInt32mf2") return static_cast<obj::BuiltinKind>(125);
  if (name == "RvvInt32m1") return static_cast<obj::BuiltinKind>(126);
  if (name == "RvvInt32m2") return static_cast<obj::BuiltinKind>(127);
  if (name == "RvvInt32m4") return static_cast<obj::BuiltinKind>(128);
  if (name == "RvvInt32m8") return static_cast<obj::BuiltinKind>(129);
  if (name == "RvvUint32mf2") return static_cast<obj::BuiltinKind>(130);
  if (name == "RvvUint32m1") return static_cast<obj::BuiltinKind>(131);
  if (name == "RvvUint32m2") return static_cast<obj::BuiltinKind>(132);
  if (name == "RvvUint32m4") return static_cast<obj::BuiltinKind>(133);
  if (name == "RvvUint32m8") return static_cast<obj::BuiltinKind>(134);
  if (name == "RvvInt64m1") return static_cast<obj::BuiltinKind>(135);
  if (name == "RvvInt64m2") return static_cast<obj::BuiltinKind>(136);
  if (name == "RvvInt64m4") return static_cast<obj::BuiltinKind>(137);
  if (name == "RvvInt64m8") return static_cast<obj::BuiltinKind>(138);
  if (name == "RvvUint64m1") return static_cast<obj::BuiltinKind>(139);
  if (name == "RvvUint64m2") return static_cast<obj::BuiltinKind>(140);
  if (name == "RvvUint64m4") return static_cast<obj::BuiltinKind>(141);
  if (name == "RvvUint64m8") return static_cast<obj::BuiltinKind>(142);
  if (name == "RvvFloat16mf4") return static_cast<obj::BuiltinKind>(143);
  if (name == "RvvFloat16mf2") return static_cast<obj::BuiltinKind>(144);
  if (name == "RvvFloat16m1") return static_cast<obj::BuiltinKind>(145);
  if (name == "RvvFloat16m2") return static_cast<obj::BuiltinKind>(146);
  if (name == "RvvFloat16m4") return static_cast<obj::BuiltinKind>(147);
  if (name == "RvvFloat16m8") return static_cast<obj::BuiltinKind>(148);
  if (name == "RvvFloat32mf2") return static_cast<obj::BuiltinKind>(149);
  if (name == "RvvFloat32m1") return static_cast<obj::BuiltinKind>(150);
  if (name == "RvvFloat32m2") return static_cast<obj::BuiltinKind>(151);
  if (name == "RvvFloat32m4") return static_cast<obj::BuiltinKind>(152);
  if (name == "RvvFloat32m8") return static_cast<obj::BuiltinKind>(153);
  if (name == "RvvFloat64m1") return static_cast<obj::BuiltinKind>(154);
  if (name == "RvvFloat64m2") return static_cast<obj::BuiltinKind>(155);
  if (name == "RvvFloat64m4") return static_cast<obj::BuiltinKind>(156);
  if (name == "RvvFloat64m8") return static_cast<obj::BuiltinKind>(157);
  if (name == "RvvBool1") return static_cast<obj::BuiltinKind>(158);
  if (name == "RvvBool2") return static_cast<obj::BuiltinKind>(159);
  if (name == "RvvBool4") return static_cast<obj::BuiltinKind>(160);
  if (name == "RvvBool8") return static_cast<obj::BuiltinKind>(161);
  if (name == "RvvBool16") return static_cast<obj::BuiltinKind>(162);
  if (name == "RvvBool32") return static_cast<obj::BuiltinKind>(163);
  if (name == "RvvBool64") return static_cast<obj::BuiltinKind>(164);
  if (name == "Void") return static_cast<obj::BuiltinKind>(165);
  if (name == "Bool") return static_cast<obj::BuiltinKind>(166);
  if (name == "Char_U") return static_cast<obj::BuiltinKind>(167);
  if (name == "UChar") return static_cast<obj::BuiltinKind>(168);
  if (name == "WChar_U") return static_cast<obj::BuiltinKind>(169);
  if (name == "Char8") return static_cast<obj::BuiltinKind>(170);
  if (name == "Char16") return static_cast<obj::BuiltinKind>(171);
  if (name == "Char32") return static_cast<obj::BuiltinKind>(172);
  if (name == "UShort") return static_cast<obj::BuiltinKind>(173);
  if (name == "UInt") return static_cast<obj::BuiltinKind>(174);
  if (name == "ULong") return static_cast<obj::BuiltinKind>(175);
  if (name == "ULongLong") return static_cast<obj::BuiltinKind>(176);
  if (name == "UInt128") return static_cast<obj::BuiltinKind>(177);
  if (name == "Char_S") return static_cast<obj::BuiltinKind>(178);
  if (name == "SChar") return static_cast<obj::BuiltinKind>(179);
  if (name == "WChar_S") return static_cast<obj::BuiltinKind>(180);
  if (name == "Short") return static_cast<obj::BuiltinKind>(181);
  if (name == "Int") return static_cast<obj::BuiltinKind>(182);
  if (name == "Long") return static_cast<obj::BuiltinKind>(183);
  if (name == "LongLong") return static_cast<obj::BuiltinKind>(184);
  if (name == "Int128") return static_cast<obj::BuiltinKind>(185);
  if (name == "ShortAccum") return static_cast<obj::BuiltinKind>(186);
  if (name == "Accum") return static_cast<obj::BuiltinKind>(187);
  if (name == "LongAccum") return static_cast<obj::BuiltinKind>(188);
  if (name == "UShortAccum") return static_cast<obj::BuiltinKind>(189);
  if (name == "UAccum") return static_cast<obj::BuiltinKind>(190);
  if (name == "ULongAccum") return static_cast<obj::BuiltinKind>(191);
  if (name == "ShortFract") return static_cast<obj::BuiltinKind>(192);
  if (name == "Fract") return static_cast<obj::BuiltinKind>(193);
  if (name == "LongFract") return static_cast<obj::BuiltinKind>(194);
  if (name == "UShortFract") return static_cast<obj::BuiltinKind>(195);
  if (name == "UFract") return static_cast<obj::BuiltinKind>(196);
  if (name == "ULongFract") return static_cast<obj::BuiltinKind>(197);
  if (name == "SatShortAccum") return static_cast<obj::BuiltinKind>(198);
  if (name == "SatAccum") return static_cast<obj::BuiltinKind>(199);
  if (name == "SatLongAccum") return static_cast<obj::BuiltinKind>(200);
  if (name == "SatUShortAccum") return static_cast<obj::BuiltinKind>(201);
  if (name == "SatUAccum") return static_cast<obj::BuiltinKind>(202);
  if (name == "SatULongAccum") return static_cast<obj::BuiltinKind>(203);
  if (name == "SatShortFract") return static_cast<obj::BuiltinKind>(204);
  if (name == "SatFract") return static_cast<obj::BuiltinKind>(205);
  if (name == "SatLongFract") return static_cast<obj::BuiltinKind>(206);
  if (name == "SatUShortFract") return static_cast<obj::BuiltinKind>(207);
  if (name == "SatUFract") return static_cast<obj::BuiltinKind>(208);
  if (name == "SatULongFract") return static_cast<obj::BuiltinKind>(209);
  if (name == "Half") return static_cast<obj::BuiltinKind>(210);
  if (name == "Float") return static_cast<obj::BuiltinKind>(211);
  if (name == "Double") return static_cast<obj::BuiltinKind>(212);
  if (name == "LongDouble") return static_cast<obj::BuiltinKind>(213);
  if (name == "Float16") return static_cast<obj::BuiltinKind>(214);
  if (name == "BFloat16") return static_cast<obj::BuiltinKind>(215);
  if (name == "Float128") return static_cast<obj::BuiltinKind>(216);
  if (name == "Ibm128") return static_cast<obj::BuiltinKind>(217);
  if (name == "NullPtr") return static_cast<obj::BuiltinKind>(218);
  if (name == "ObjCId") return static_cast<obj::BuiltinKind>(219);
  if (name == "ObjCClass") return static_cast<obj::BuiltinKind>(220);
  if (name == "ObjCSel") return static_cast<obj::BuiltinKind>(221);
  if (name == "OCLSampler") return static_cast<obj::BuiltinKind>(222);
  if (name == "OCLEvent") return static_cast<obj::BuiltinKind>(223);
  if (name == "OCLClkEvent") return static_cast<obj::BuiltinKind>(224);
  if (name == "OCLQueue") return static_cast<obj::BuiltinKind>(225);
  if (name == "OCLReserveID") return static_cast<obj::BuiltinKind>(226);
  if (name == "Dependent") return static_cast<obj::BuiltinKind>(227);
  if (name == "Overload") return static_cast<obj::BuiltinKind>(228);
  if (name == "BoundMember") return static_cast<obj::BuiltinKind>(229);
  if (name == "PseudoObject") return static_cast<obj::BuiltinKind>(230);
  if (name == "UnknownAny") return static_cast<obj::BuiltinKind>(231);
  if (name == "BuiltinFn") return static_cast<obj::BuiltinKind>(232);
  if (name == "ARCUnbridgedCast") return static_cast<obj::BuiltinKind>(233);
  if (name == "IncompleteMatrixIdx") return static_cast<obj::BuiltinKind>(234);
  if (name == "OMPArraySection") return static_cast<obj::BuiltinKind>(235);
  if (name == "OMPArrayShaping") return static_cast<obj::BuiltinKind>(236);
  if (name == "OMPIterator") return static_cast<obj::BuiltinKind>(237);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::C99Qualifier enumValue<obj::C99Qualifier>(std::string_view name) {
  if (name == "CONST") return static_cast<obj::C99Qualifier>(0);
  if (name == "RESTRICT") return static_cast<obj::C99Qualifier>(1);
  if (name == "RESTRICT_C99") return static_cast<obj::C99Qualifier>(2);
  if (name == "VOLATILE") return static_cast<obj::C99Qualifier>(3);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::CallingConvention enumValue<obj::CallingConvention>(std::string_view name) {
  if (name == "C") return static_cast<obj::CallingConvention>(0);
  if (name == "X86StdCall") return static_cast<obj::CallingConvention>(1);
  if (name == "X86FastCall") return static_cast<obj::CallingConvention>(2);
  if (name == "X86ThisCall") return static_cast<obj::CallingConvention>(3);
  if (name == "X86VectorCall") return static_cast<obj::CallingConvention>(4);
  if (name == "X86Pascal") return static_cast<obj::CallingConvention>(5);
  if (name == "Win64") return static_cast<obj::CallingConvention>(6);
  if (name == "X86_64SysV") return static_cast<obj::CallingConvention>(7);
  if (name == "X86RegCall") return static_cast<obj::CallingConvention>(8);
  if (name == "AAPCS") return static_cast<obj::CallingConvention>(9);
  if (name == "AAPCS_VFP") return static_cast<obj::CallingConvention>(10);
  if (name == "IntelOclBicc") return static_cast<obj::CallingConvention>(11);
  if (name == "SpirFunction") return static_cast<obj::CallingConvention>(12);
  if (name == "OpenCLKernel") return static_cast<obj::CallingConvention>(13);
  if (name == "Swift") return static_cast<obj::CallingConvention>(14);
  if (name == "SwiftAsync") return static_cast<obj::CallingConvention>(15);
  if (name == "PreserveMost") return static_cast<obj::CallingConvention>(16);
  if (name == "PreserveAll") return static_cast<obj::CallingConvention>(17);
  if (name == "AArch64VectorCall") return static_cast<obj::CallingConvention>(18);
  if (name == "AArch64SVEPCS") return static_cast<obj::CallingConvention>(19);
  if (name == "AMDGPUKernelCall") return static_cast<obj::CallingConvention>(20);
  if (name == "M68kRTD") return static_cast<obj::CallingConvention>(21);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ElaboratedTypeKeyword enumValue<obj::ElaboratedTypeKeyword>(std::string_view name) {
  if (name == "Struct") return static_cast<obj::ElaboratedTypeKeyword>(0);
  if (name == "Interface") return static_cast<obj::ElaboratedTypeKeyword>(1);
  if (name == "Union") return static_cast<obj::ElaboratedTypeKeyword>(2);
  if (name == "Class") return static_cast<obj::ElaboratedTypeKeyword>(3);
  if (name == "Enum") return static_cast<obj::ElaboratedTypeKeyword>(4);
  if (name == "Typename") return static_cast<obj::ElaboratedTypeKeyword>(5);
  if (name == "None") return static_cast<obj::ElaboratedTypeKeyword>(6);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ExceptionSpecificationType enumValue<obj::ExceptionSpecificationType>(std::string_view name) {
  if (name == "None") return static_cast<obj::ExceptionSpecificationType>(0);
  if (name == "DynamicNone") return static_cast<obj::ExceptionSpecificationType>(1);
  if (name == "Dynamic") return static_cast<obj::ExceptionSpecificationType>(2);
  if (name == "MSAny") return static_cast<obj::ExceptionSpecificationType>(3);
  if (name == "NoThrow") return static_cast<obj::ExceptionSpecificationType>(4);
  if (name == "BasicNoexcept") return static_cast<obj::ExceptionSpecificationType>(5);
  if (name == "DependentNoexcept") return static_cast<obj::ExceptionSpecificationType>(6);
  if (name == "NoexceptFalse") return static_cast<obj::ExceptionSpecificationType>(7);
  if (name == "NoexceptTrue") return static_cast<obj::ExceptionSpecificationType>(8);
  if (name == "Unevaluated") return static_cast<obj::ExceptionSpecificationType>(9);
  if (name == "Uninstantiated") return static_cast<obj::ExceptionSpecificationType>(10);
  if (name == "Unparsed") return static_cast<obj::ExceptionSpecificationType>(11);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TypeDependency enumValue<obj::TypeDependency>(std::string_view name) {
  if (name == "DEPENDENT") return static_cast<obj::TypeDependency>(0);
  if (name == "INSTANTIATION_DEPENDENT") return static_cast<obj::TypeDependency>(1);
  if (name == "NONE") return static_cast<obj::TypeDependency>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::UnaryTransformTypeKind enumValue<obj::UnaryTransformTypeKind>(std::string_view name) {
  if (name == "AddLvalueReference") return static_cast<obj::UnaryTransformTypeKind>(0);
  if (name == "AddPointer") return static_cast<obj::UnaryTransformTypeKind>(1);
  if (name == "AddRvalueReference") return static_cast<obj::UnaryTransformTypeKind>(2);
  if (name == "Decay") return static_cast<obj::UnaryTransformTypeKind>(3);
  if (name == "MakeSigned") return static_cast<obj::UnaryTransformTypeKind>(4);
  if (name == "MakeUnsigned") return static_cast<obj::UnaryTransformTypeKind>(5);
  if (name == "RemoveAllExtents") return static_cast<obj::UnaryTransformTypeKind>(6);
  if (name == "RemoveConst") return static_cast<obj::UnaryTransformTypeKind>(7);
  if (name == "RemoveCV") return static_cast<obj::UnaryTransformTypeKind>(8);
  if (name == "RemoveCVRef") return static_cast<obj::UnaryTransformTypeKind>(9);
  if (name == "RemoveExtent") return static_cast<obj::UnaryTransformTypeKind>(10);
  if (name == "RemovePointer") return static_cast<obj::UnaryTransformTypeKind>(11);
  if (name == "RemoveReference") return static_cast<obj::UnaryTransformTypeKind>(12);
  if (name == "RemoveRestrict") return static_cast<obj::UnaryTransformTypeKind>(13);
  if (name == "RemoveVolatile") return static_cast<obj::UnaryTransformTypeKind>(14);
  if (name == "EnumUnderlyingType") return static_cast<obj::UnaryTransformTypeKind>(15);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::AccessSpecifier enumValue<obj::AccessSpecifier>(std::string_view name) {
  if (name == "PUBLIC") return static_cast<obj::AccessSpecifier>(0);
  if (name == "PROTECTED") return static_cast<obj::AccessSpecifier>(1);
  if (name == "PRIVATE") return static_cast<obj::AccessSpecifier>(2);
  if (name == "NONE") return static_cast<obj::AccessSpecifier>(3);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::CastKind enumValue<obj::CastKind>(std::string_view name) {
  if (name == "Dependent") return static_cast<obj::CastKind>(0);
  if (name == "BitCast") return static_cast<obj::CastKind>(1);
  if (name == "LValueBitCast") return static_cast<obj::CastKind>(2);
  if (name == "LValueToRValueBitCast") return static_cast<obj::CastKind>(3);
  if (name == "LValueToRValue") return static_cast<obj::CastKind>(4);
  if (name == "NoOp") return static_cast<obj::CastKind>(5);
  if (name == "BaseToDerived") return static_cast<obj::CastKind>(6);
  if (name == "DerivedToBase") return static_cast<obj::CastKind>(7);
  if (name == "UncheckedDerivedToBase") return static_cast<obj::CastKind>(8);
  if (name == "Dynamic") return static_cast<obj::CastKind>(9);
  if (name == "ToUnion") return static_cast<obj::CastKind>(10);
  if (name == "ArrayToPointerDecay") return static_cast<obj::CastKind>(11);
  if (name == "FunctionToPointerDecay") return static_cast<obj::CastKind>(12);
  if (name == "NullToPointer") return static_cast<obj::CastKind>(13);
  if (name == "NullToMemberPointer") return static_cast<obj::CastKind>(14);
  if (name == "BaseToDerivedMemberPointer") return static_cast<obj::CastKind>(15);
  if (name == "DerivedToBaseMemberPointer") return static_cast<obj::CastKind>(16);
  if (name == "MemberPointerToBoolean") return static_cast<obj::CastKind>(17);
  if (name == "ReinterpretMemberPointer") return static_cast<obj::CastKind>(18);
  if (name == "UserDefinedConversion") return static_cast<obj::CastKind>(19);
  if (name == "ConstructorConversion") return static_cast<obj::CastKind>(20);
  if (name == "IntegralToPointer") return static_cast<obj::CastKind>(21);
  if (name == "PointerToIntegral") return static_cast<obj::CastKind>(22);
  if (name == "PointerToBoolean") return static_cast<obj::CastKind>(23);
  if (name == "ToVoid") return static_cast<obj::CastKind>(24);
  if (name == "MatrixCast") return static_cast<obj::CastKind>(25);
  if (name == "VectorSplat") return static_cast<obj::CastKind>(26);
  if (name == "IntegralCast") return static_cast<obj::CastKind>(27);
  if (name == "IntegralToBoolean") return static_cast<obj::CastKind>(28);
  if (name == "IntegralToFloating") return static_cast<obj::CastKind>(29);
  if (name == "FloatingToFixedPoint") return static_cast<obj::CastKind>(30);
  if (name == "FixedPointToFloating") return static_cast<obj::CastKind>(31);
  if (name == "FixedPointCast") return static_cast<obj::CastKind>(32);
  if (name == "FixedPointToIntegral") return static_cast<obj::CastKind>(33);
  if (name == "IntegralToFixedPoint") return static_cast<obj::CastKind>(34);
  if (name == "FixedPointToBoolean") return static_cast<obj::CastKind>(35);
  if (name == "FloatingToIntegral") return static_cast<obj::CastKind>(36);
  if (name == "FloatingToBoolean") return static_cast<obj::CastKind>(37);
  if (name == "BooleanToSignedIntegral") return static_cast<obj::CastKind>(38);
  if (name == "FloatingCast") return static_cast<obj::CastKind>(39);
  if (name == "CPointerToObjCPointerCast") return static_cast<obj::CastKind>(40);
  if (name == "BlockPointerToObjCPointerCast") return static_cast<obj::CastKind>(41);
  if (name == "AnyPointerToBlockPointerCast") return static_cast<obj::CastKind>(42);
  if (name == "ObjCObjectLValueCast") return static_cast<obj::CastKind>(43);
  if (name == "FloatingRealToComplex") return static_cast<obj::CastKind>(44);
  if (name == "FloatingComplexToReal") return static_cast<obj::CastKind>(45);
  if (name == "FloatingComplexToBoolean") return static_cast<obj::CastKind>(46);
  if (name == "FloatingComplexCast") return static_cast<obj::CastKind>(47);
  if (name == "FloatingComplexToIntegralComplex") return static_cast<obj::CastKind>(48);
  if (name == "IntegralRealToComplex") return static_cast<obj::CastKind>(49);
  if (name == "IntegralComplexToReal") return static_cast<obj::CastKind>(50);
  if (name == "IntegralComplexToBoolean") return static_cast<obj::CastKind>(51);
  if (name == "IntegralComplexCast") return static_cast<obj::CastKind>(52);
  if (name == "IntegralComplexToFloatingComplex") return static_cast<obj::CastKind>(53);
  if (name == "ARCProduceObject") return static_cast<obj::CastKind>(54);
  if (name == "ARCConsumeObject") return static_cast<obj::CastKind>(55);
  if (name == "ARCReclaimReturnedObject") return static_cast<obj::CastKind>(56);
  if (name == "ARCExtendBlockObject") return static_cast<obj::CastKind>(57);
  if (name == "AtomicToNonAtomic") return static_cast<obj::CastKind>(58);
  if (name == "NonAtomicToAtomic") return static_cast<obj::CastKind>(59);
  if (name == "CopyAndAutoreleaseBlockObject") return static_cast<obj::CastKind>(60);
  if (name == "BuiltinFnToFnPtr") return static_cast<obj::CastKind>(61);
  if (name == "ZeroToOCLOpaqueType") return static_cast<obj::CastKind>(62);
  if (name == "AddressSpaceConversion") return static_cast<obj::CastKind>(63);
  if (name == "IntToOCLSampler") return static_cast<obj::CastKind>(64);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::ReferenceQualifier enumValue<obj::ReferenceQualifier>(std::string_view name) {
  if (name == "LValue") return static_cast<obj::ReferenceQualifier>(0);
  if (name == "RValue") return static_cast<obj::ReferenceQualifier>(1);
  if (name == "None") return static_cast<obj::ReferenceQualifier>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TLSKind enumValue<obj::TLSKind>(std::string_view name) {
  if (name == "NONE") return static_cast<obj::TLSKind>(0);
  if (name == "STATIC") return static_cast<obj::TLSKind>(1);
  if (name == "DYNAMIC") return static_cast<obj::TLSKind>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TagKind enumValue<obj::TagKind>(std::string_view name) {
  if (name == "STRUCT" || name == "Struct") return static_cast<obj::TagKind>(0);
  if (name == "INTERFACE" || name == "Interface") return static_cast<obj::TagKind>(1);
  if (name == "UNION" || name == "Union") return static_cast<obj::TagKind>(2);
  if (name == "CLASS" || name == "Class") return static_cast<obj::TagKind>(3);
  if (name == "ENUM" || name == "Enum") return static_cast<obj::TagKind>(4);
  if (name == "NO_KIND" || name == "NoKind") return static_cast<obj::TagKind>(5);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::TemplateTypeParmKind enumValue<obj::TemplateTypeParmKind>(std::string_view name) {
  if (name == "TYPENAME") return static_cast<obj::TemplateTypeParmKind>(0);
  if (name == "CLASS") return static_cast<obj::TemplateTypeParmKind>(1);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::UnaryExprOrTypeTrait enumValue<obj::UnaryExprOrTypeTrait>(std::string_view name) {
  if (name == "SizeOf") return static_cast<obj::UnaryExprOrTypeTrait>(0);
  if (name == "AlignOf") return static_cast<obj::UnaryExprOrTypeTrait>(1);
  if (name == "PreferredAlignOf") return static_cast<obj::UnaryExprOrTypeTrait>(2);
  if (name == "VecStep") return static_cast<obj::UnaryExprOrTypeTrait>(3);
  if (name == "OpenMPRequiredSimdAlign") return static_cast<obj::UnaryExprOrTypeTrait>(4);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
template <> inline obj::EnumScopeType enumValue<obj::EnumScopeType>(std::string_view name) {
  if (name == "CLASS") return static_cast<obj::EnumScopeType>(0);
  if (name == "STRUCT") return static_cast<obj::EnumScopeType>(1);
  if (name == "NO_SCOPE") return static_cast<obj::EnumScopeType>(2);
  throw std::invalid_argument("Unknown wire enum: "+std::string(name));
}
struct Context {
  clang::ASTContext *ast;
  int id;
  std::function<uint32_t(llvm::StringRef)> fileId;
};
int64_t wireId(const std::string &value);
std::unique_ptr<obj::NodeDataT> makeNodeData(clang::SourceLocation begin, clang::SourceLocation end, Context &c);
std::string qualifierString(clang::NestedNameSpecifier *qualifier, Context &c);
std::string sourceText(clang::SourceRange range, Context &c);
std::vector<obj::C99Qualifier> c99Qualifiers(clang::Qualifiers qualifiers, Context &c);
std::unique_ptr<obj::TemplateArgumentT> makeTemplateArgument(const clang::TemplateArgument &arg, Context &c);
std::unique_ptr<obj::TemplateNameT> makeTemplateName(const clang::TemplateName &name, Context &c);
std::unique_ptr<obj::CXXBaseSpecifierT> makeCXXBaseSpecifier(const clang::CXXBaseSpecifier &base, Context &c);
std::unique_ptr<obj::CXXCtorInitializerT> makeCXXCtorInitializer(const clang::CXXCtorInitializer *init, Context &c);
std::unique_ptr<obj::ExplicitSpecifierT> makeExplicitSpecifier(const clang::ExplicitSpecifier &specifier, Context &c);
std::unique_ptr<obj::ExceptionSpecificationT> makeExceptionSpecification(const clang::FunctionProtoType *type, Context &c);
std::unique_ptr<obj::OffsetOfComponentT> makeOffsetOfComponent(const clang::OffsetOfExpr *expr, unsigned index, Context &c);
std::unique_ptr<obj::DesignatorT> makeDesignator(const clang::DesignatedInitExpr::Designator *designator, Context &c);
std::unique_ptr<obj::NestedNameSpecifierT> makeNestedNameSpecifier(clang::NestedNameSpecifier *specifier, Context &c);

// Handler declarations are generated from the direct native definitions.
#include "ProtoHandlerDeclarations.inc"
}
#endif
