#pragma once
// Generated from protoc's FileDescriptorSet; do not edit by hand.
#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <type_traits>
#include <typeindex>
#include <utility>
#include <vector>

namespace astwire::v1obj {

struct RangeT;
struct SourceInfoT;
struct NodeDataT;
struct CXXBaseSpecifierT;
struct ExplicitSpecifierT;
struct TemplateDeclarationT;
struct TemplateNullPtrT;
struct TemplateTypeT;
struct TemplateExpressionT;
struct TemplatePackT;
struct TemplateIntegralT;
struct TemplateExpansionT;
struct TemplateStructuralValueT;
struct TemplateArgumentT;
struct DirectTemplateNameT;
struct QualifiedTemplateNameT;
struct SubstitutedTemplateNameT;
struct UsingTemplateNameT;
struct DependentTemplateNameT;
struct TemplateNameT;
struct AnyMemberInitializerT;
struct BaseInitializerT;
struct DelegatingInitializerT;
struct CXXCtorInitializerT;
struct NoExceptionDetailsT;
struct ComputedExceptionDetailsT;
struct UnevaluatedExceptionDetailsT;
struct UninstantiatedExceptionDetailsT;
struct ExceptionSpecificationT;
struct OffsetArrayT;
struct OffsetFieldT;
struct OffsetIdentifierT;
struct OffsetBaseT;
struct OffsetOfComponentT;
struct FieldDesignatorT;
struct ArrayDesignatorT;
struct ArrayRangeDesignatorT;
struct DesignatorT;
struct AsmInputT;
struct AsmOutputT;
struct NamespaceSpecifierT;
struct NamespaceAliasSpecifierT;
struct TypeSpecifierT;
struct TypeWithTemplateSpecifierT;
struct GlobalSpecifierT;
struct SuperSpecifierT;
struct NestedNameSpecifierT;
struct DeclDataT;
struct NamedDeclDataT;
struct TypeDeclDataT;
struct TagDeclDataT;
struct RecordDeclDataT;
struct ValueDeclDataT;
struct DeclaratorDeclDataT;
struct TemplateDeclDataT;
struct FunctionDeclDataT;
struct CXXMethodDeclDataT;
struct CXXConstructorDeclDataT;
struct CXXConversionDeclDataT;
struct FieldDeclDataT;
struct ParmVarDeclDataT;
struct VarDeclDataT;
struct TemplateTypeParmDeclDataT;
struct UnresolvedUsingTypenameDeclDataT;
struct EnumDeclDataT;
struct CXXRecordDeclDataT;
struct ClassTemplateSpecializationDeclDataT;
struct NonTypeTemplateParmDeclDataT;
struct TypedefNameDeclDataT;
struct AccessSpecDeclDataT;
struct UsingDeclDataT;
struct UsingDirectiveDeclDataT;
struct NamespaceDeclDataT;
struct NamespaceAliasDeclDataT;
struct LinkageSpecDeclDataT;
struct StaticAssertDeclDataT;
struct TemplateTemplateParmDeclDataT;
struct MSPropertyDeclDataT;
struct ClassTemplatePartialSpecializationDeclDataT;
struct TypeDataT;
struct QualTypeDataT;
struct BuiltinTypeDataT;
struct PointerTypeDataT;
struct FunctionTypeDataT;
struct FunctionProtoTypeDataT;
struct ArrayTypeDataT;
struct ConstantArrayTypeDataT;
struct VariableArrayTypeDataT;
struct DependentSizedArrayTypeDataT;
struct TagTypeDataT;
struct TypeWithKeywordDataT;
struct ElaboratedTypeDataT;
struct TemplateTypeParmTypeDataT;
struct TemplateSpecializationTypeDataT;
struct TypedefTypeDataT;
struct AdjustedTypeDataT;
struct DecayedTypeDataT;
struct DecltypeTypeDataT;
struct AutoTypeDataT;
struct ReferenceTypeDataT;
struct TypeOfExprTypeDataT;
struct PackExpansionTypeDataT;
struct UnaryTransformTypeDataT;
struct AttributedTypeDataT;
struct SubstTemplateTypeParmTypeDataT;
struct ComplexTypeDataT;
struct ExprDataT;
struct CastExprDataT;
struct LiteralDataT;
struct CharacterLiteralDataT;
struct IntegerLiteralDataT;
struct FloatingLiteralDataT;
struct StringLiteralDataT;
struct CXXBoolLiteralExprDataT;
struct CompoundLiteralExprDataT;
struct InitListExprDataT;
struct DeclRefExprDataT;
struct OverloadExprDataT;
struct CXXConstructExprDataT;
struct CXXTemporaryObjectExprDataT;
struct MemberExprDataT;
struct MaterializeTemporaryExprDataT;
struct BinaryOperatorDataT;
struct UnresolvedMemberExprDataT;
struct UnresolvedLookupExprDataT;
struct CallExprDataT;
struct CXXMemberCallExprDataT;
struct CXXTypeidExprDataT;
struct ExplicitCastExprDataT;
struct CXXNamedCastExprDataT;
struct CXXDependentScopeMemberExprDataT;
struct UnaryOperatorDataT;
struct UnaryExprOrTypeTraitExprDataT;
struct CXXNewExprDataT;
struct CXXDeleteExprDataT;
struct OffsetOfExprDataT;
struct LambdaExprDataT;
struct PredefinedExprDataT;
struct SizeOfPackExprDataT;
struct ArrayInitLoopExprDataT;
struct DesignatedInitExprDataT;
struct DependentScopeDeclRefExprDataT;
struct CXXNoexceptExprDataT;
struct CXXPseudoDestructorExprDataT;
struct PseudoObjectExprDataT;
struct MSPropertyRefExprDataT;
struct StmtDataT;
struct LabelStmtDataT;
struct GotoStmtDataT;
struct AttributedStmtDataT;
struct AsmStmtDataT;
struct GCCAsmStmtDataT;
struct MSAsmStmtDataT;
struct AttributeDataT;
struct AlignedAttrDataT;
struct OpenCLUnrollHintAttrDataT;
struct FormatAttrDataT;
struct NonNullAttrDataT;
struct VisibilityAttrDataT;
struct FileT;
struct ChildrenT;
struct NodeClassT;
struct TopLevelT;
struct IncludeT;
struct PragmaT;
struct TranslationUnitFileT;
struct CounterT;
struct LanguageT;
struct NodeT;

// Lightweight per-record object model used only while converting one native
// record to generated protobuf classes. It is deliberately not an AST store
// and is never retained as a second protobuf AST.
struct UnionValue {
  std::shared_ptr<void> object;
  std::type_index type = typeid(void);
  template <class T> void Set(T &&value) {
    using U = std::decay_t<T>;
    object = std::make_shared<U>(std::forward<T>(value));
    type = typeid(U);
  }
  template <class T> const T *get() const {
    return type == typeid(T) ? static_cast<const T *>(object.get()) : nullptr;
  }
};

enum class TopLevelKind : int32_t { TOPLEVELKIND_DECL = 0, TOPLEVELKIND_TYPE = 1, TOPLEVELKIND_ATTR = 2, };
enum class AttributeKind : int32_t { ATTRIBUTEKIND_ADDRESSSPACE = 0, ATTRIBUTEKIND_ANNOTATETYPE = 1, ATTRIBUTEKIND_ARMIN = 2, ATTRIBUTEKIND_ARMINOUT = 3, ATTRIBUTEKIND_ARMMVESTRICTPOLYMORPHISM = 4, ATTRIBUTEKIND_ARMOUT = 5, ATTRIBUTEKIND_ARMPRESERVES = 6, ATTRIBUTEKIND_ARMSTREAMING = 7, ATTRIBUTEKIND_ARMSTREAMINGCOMPATIBLE = 8, ATTRIBUTEKIND_BTFTYPETAG = 9, ATTRIBUTEKIND_CMSENSCALL = 10, ATTRIBUTEKIND_HLSLGROUPSHAREDADDRESSSPACE = 11, ATTRIBUTEKIND_HLSLPARAMMODIFIER = 12, ATTRIBUTEKIND_NODEREF = 13, ATTRIBUTEKIND_OBJCGC = 14, ATTRIBUTEKIND_OBJCINERTUNSAFEUNRETAINED = 15, ATTRIBUTEKIND_OBJCKINDOF = 16, ATTRIBUTEKIND_OPENCLCONSTANTADDRESSSPACE = 17, ATTRIBUTEKIND_OPENCLGENERICADDRESSSPACE = 18, ATTRIBUTEKIND_OPENCLGLOBALADDRESSSPACE = 19, ATTRIBUTEKIND_OPENCLGLOBALDEVICEADDRESSSPACE = 20, ATTRIBUTEKIND_OPENCLGLOBALHOSTADDRESSSPACE = 21, ATTRIBUTEKIND_OPENCLLOCALADDRESSSPACE = 22, ATTRIBUTEKIND_OPENCLPRIVATEADDRESSSPACE = 23, ATTRIBUTEKIND_PTR32 = 24, ATTRIBUTEKIND_PTR64 = 25, ATTRIBUTEKIND_SPTR = 26, ATTRIBUTEKIND_TYPENONNULL = 27, ATTRIBUTEKIND_TYPENULLUNSPECIFIED = 28, ATTRIBUTEKIND_TYPENULLABLE = 29, ATTRIBUTEKIND_TYPENULLABLERESULT = 30, ATTRIBUTEKIND_UPTR = 31, ATTRIBUTEKIND_WEBASSEMBLYFUNCREF = 32, ATTRIBUTEKIND_CODEALIGN = 33, ATTRIBUTEKIND_FALLTHROUGH = 34, ATTRIBUTEKIND_LIKELY = 35, ATTRIBUTEKIND_MUSTTAIL = 36, ATTRIBUTEKIND_OPENCLUNROLLHINT = 37, ATTRIBUTEKIND_UNLIKELY = 38, ATTRIBUTEKIND_ALWAYSINLINE = 39, ATTRIBUTEKIND_NOINLINE = 40, ATTRIBUTEKIND_NOMERGE = 41, ATTRIBUTEKIND_SUPPRESS = 42, ATTRIBUTEKIND_AARCH64SVEPCS = 43, ATTRIBUTEKIND_AARCH64VECTORPCS = 44, ATTRIBUTEKIND_AMDGPUKERNELCALL = 45, ATTRIBUTEKIND_ACQUIREHANDLE = 46, ATTRIBUTEKIND_ANYX86NOCFCHECK = 47, ATTRIBUTEKIND_CDECL = 48, ATTRIBUTEKIND_FASTCALL = 49, ATTRIBUTEKIND_INTELOCLBICC = 50, ATTRIBUTEKIND_LIFETIMEBOUND = 51, ATTRIBUTEKIND_M68KRTD = 52, ATTRIBUTEKIND_MSABI = 53, ATTRIBUTEKIND_NSRETURNSRETAINED = 54, ATTRIBUTEKIND_OBJCOWNERSHIP = 55, ATTRIBUTEKIND_PASCAL = 56, ATTRIBUTEKIND_PCS = 57, ATTRIBUTEKIND_PRESERVEALL = 58, ATTRIBUTEKIND_PRESERVEMOST = 59, ATTRIBUTEKIND_REGCALL = 60, ATTRIBUTEKIND_STDCALL = 61, ATTRIBUTEKIND_SWIFTASYNCCALL = 62, ATTRIBUTEKIND_SWIFTCALL = 63, ATTRIBUTEKIND_SYSVABI = 64, ATTRIBUTEKIND_THISCALL = 65, ATTRIBUTEKIND_VECTORCALL = 66, ATTRIBUTEKIND_SWIFTASYNCCONTEXT = 67, ATTRIBUTEKIND_SWIFTCONTEXT = 68, ATTRIBUTEKIND_SWIFTERRORRESULT = 69, ATTRIBUTEKIND_SWIFTINDIRECTRESULT = 70, ATTRIBUTEKIND_ANNOTATE = 71, ATTRIBUTEKIND_CFCONSUMED = 72, ATTRIBUTEKIND_CARRIESDEPENDENCY = 73, ATTRIBUTEKIND_NSCONSUMED = 74, ATTRIBUTEKIND_NONNULL = 75, ATTRIBUTEKIND_OSCONSUMED = 76, ATTRIBUTEKIND_PASSOBJECTSIZE = 77, ATTRIBUTEKIND_RELEASEHANDLE = 78, ATTRIBUTEKIND_USEHANDLE = 79, ATTRIBUTEKIND_HLSLSV_DISPATCHTHREADID = 80, ATTRIBUTEKIND_HLSLSV_GROUPINDEX = 81, ATTRIBUTEKIND_AMDGPUFLATWORKGROUPSIZE = 82, ATTRIBUTEKIND_AMDGPUNUMSGPR = 83, ATTRIBUTEKIND_AMDGPUNUMVGPR = 84, ATTRIBUTEKIND_AMDGPUWAVESPEREU = 85, ATTRIBUTEKIND_ARMINTERRUPT = 86, ATTRIBUTEKIND_AVRINTERRUPT = 87, ATTRIBUTEKIND_AVRSIGNAL = 88, ATTRIBUTEKIND_ACQUIRECAPABILITY = 89, ATTRIBUTEKIND_ACQUIREDAFTER = 90, ATTRIBUTEKIND_ACQUIREDBEFORE = 91, ATTRIBUTEKIND_ALIGNMAC68K = 92, ATTRIBUTEKIND_ALIGNNATURAL = 93, ATTRIBUTEKIND_ALIGNED = 94, ATTRIBUTEKIND_ALLOCALIGN = 95, ATTRIBUTEKIND_ALLOCSIZE = 96, ATTRIBUTEKIND_ALWAYSDESTROY = 97, ATTRIBUTEKIND_ANALYZERNORETURN = 98, ATTRIBUTEKIND_ANYX86INTERRUPT = 99, ATTRIBUTEKIND_ANYX86NOCALLERSAVEDREGISTERS = 100, ATTRIBUTEKIND_ARCWEAKREFUNAVAILABLE = 101, ATTRIBUTEKIND_ARGUMENTWITHTYPETAG = 102, ATTRIBUTEKIND_ARMBUILTINALIAS = 103, ATTRIBUTEKIND_ARMLOCALLYSTREAMING = 104, ATTRIBUTEKIND_ARMNEW = 105, ATTRIBUTEKIND_ARTIFICIAL = 106, ATTRIBUTEKIND_ASMLABEL = 107, ATTRIBUTEKIND_ASSERTCAPABILITY = 108, ATTRIBUTEKIND_ASSERTEXCLUSIVELOCK = 109, ATTRIBUTEKIND_ASSERTSHAREDLOCK = 110, ATTRIBUTEKIND_ASSUMEALIGNED = 111, ATTRIBUTEKIND_ASSUMPTION = 112, ATTRIBUTEKIND_AVAILABILITY = 113, ATTRIBUTEKIND_AVAILABLEONLYINDEFAULTEVALMETHOD = 114, ATTRIBUTEKIND_BPFPRESERVEACCESSINDEX = 115, ATTRIBUTEKIND_BPFPRESERVESTATICOFFSET = 116, ATTRIBUTEKIND_BTFDECLTAG = 117, ATTRIBUTEKIND_BLOCKS = 118, ATTRIBUTEKIND_BUILTIN = 119, ATTRIBUTEKIND_C11NORETURN = 120, ATTRIBUTEKIND_CFAUDITEDTRANSFER = 121, ATTRIBUTEKIND_CFGUARD = 122, ATTRIBUTEKIND_CFICANONICALJUMPTABLE = 123, ATTRIBUTEKIND_CFRETURNSNOTRETAINED = 124, ATTRIBUTEKIND_CFRETURNSRETAINED = 125, ATTRIBUTEKIND_CFUNKNOWNTRANSFER = 126, ATTRIBUTEKIND_CPUDISPATCH = 127, ATTRIBUTEKIND_CPUSPECIFIC = 128, ATTRIBUTEKIND_CUDACONSTANT = 129, ATTRIBUTEKIND_CUDADEVICE = 130, ATTRIBUTEKIND_CUDADEVICEBUILTINSURFACETYPE = 131, ATTRIBUTEKIND_CUDADEVICEBUILTINTEXTURETYPE = 132, ATTRIBUTEKIND_CUDAGLOBAL = 133, ATTRIBUTEKIND_CUDAHOST = 134, ATTRIBUTEKIND_CUDAINVALIDTARGET = 135, ATTRIBUTEKIND_CUDALAUNCHBOUNDS = 136, ATTRIBUTEKIND_CUDASHARED = 137, ATTRIBUTEKIND_CXX11NORETURN = 138, ATTRIBUTEKIND_CALLABLEWHEN = 139, ATTRIBUTEKIND_CALLBACK = 140, ATTRIBUTEKIND_CAPABILITY = 141, ATTRIBUTEKIND_CAPTUREDRECORD = 142, ATTRIBUTEKIND_CLEANUP = 143, ATTRIBUTEKIND_CMSENSENTRY = 144, ATTRIBUTEKIND_CODEMODEL = 145, ATTRIBUTEKIND_CODESEG = 146, ATTRIBUTEKIND_COLD = 147, ATTRIBUTEKIND_COMMON = 148, ATTRIBUTEKIND_CONST = 149, ATTRIBUTEKIND_CONSTINIT = 150, ATTRIBUTEKIND_CONSTRUCTOR = 151, ATTRIBUTEKIND_CONSUMABLE = 152, ATTRIBUTEKIND_CONSUMABLEAUTOCAST = 153, ATTRIBUTEKIND_CONSUMABLESETONREAD = 154, ATTRIBUTEKIND_CONVERGENT = 155, ATTRIBUTEKIND_CORODISABLELIFETIMEBOUND = 156, ATTRIBUTEKIND_COROLIFETIMEBOUND = 157, ATTRIBUTEKIND_COROONLYDESTROYWHENCOMPLETE = 158, ATTRIBUTEKIND_CORORETURNTYPE = 159, ATTRIBUTEKIND_COROWRAPPER = 160, ATTRIBUTEKIND_COUNTEDBY = 161, ATTRIBUTEKIND_DLLEXPORT = 162, ATTRIBUTEKIND_DLLEXPORTSTATICLOCAL = 163, ATTRIBUTEKIND_DLLIMPORT = 164, ATTRIBUTEKIND_DLLIMPORTSTATICLOCAL = 165, ATTRIBUTEKIND_DEPRECATED = 166, ATTRIBUTEKIND_DESTRUCTOR = 167, ATTRIBUTEKIND_DIAGNOSEASBUILTIN = 168, ATTRIBUTEKIND_DIAGNOSEIF = 169, ATTRIBUTEKIND_DISABLESANITIZERINSTRUMENTATION = 170, ATTRIBUTEKIND_DISABLETAILCALLS = 171, ATTRIBUTEKIND_EMPTYBASES = 172, ATTRIBUTEKIND_ENABLEIF = 173, ATTRIBUTEKIND_ENFORCETCB = 174, ATTRIBUTEKIND_ENFORCETCBLEAF = 175, ATTRIBUTEKIND_ENUMEXTENSIBILITY = 176, ATTRIBUTEKIND_ERROR = 177, ATTRIBUTEKIND_EXCLUDEFROMEXPLICITINSTANTIATION = 178, ATTRIBUTEKIND_EXCLUSIVETRYLOCKFUNCTION = 179, ATTRIBUTEKIND_EXTERNALSOURCESYMBOL = 180, ATTRIBUTEKIND_FINAL = 181, ATTRIBUTEKIND_FLAGENUM = 182, ATTRIBUTEKIND_FLATTEN = 183, ATTRIBUTEKIND_FORMAT = 184, ATTRIBUTEKIND_FORMATARG = 185, ATTRIBUTEKIND_FUNCTIONRETURNTHUNKS = 186, ATTRIBUTEKIND_GNUINLINE = 187, ATTRIBUTEKIND_GUARDEDBY = 188, ATTRIBUTEKIND_GUARDEDVAR = 189, ATTRIBUTEKIND_HIPMANAGED = 190, ATTRIBUTEKIND_HLSLNUMTHREADS = 191, ATTRIBUTEKIND_HLSLRESOURCE = 192, ATTRIBUTEKIND_HLSLRESOURCEBINDING = 193, ATTRIBUTEKIND_HLSLSHADER = 194, ATTRIBUTEKIND_HOT = 195, ATTRIBUTEKIND_IBACTION = 196, ATTRIBUTEKIND_IBOUTLET = 197, ATTRIBUTEKIND_IBOUTLETCOLLECTION = 198, ATTRIBUTEKIND_INITPRIORITY = 199, ATTRIBUTEKIND_INTERNALLINKAGE = 200, ATTRIBUTEKIND_LTOVISIBILITYPUBLIC = 201, ATTRIBUTEKIND_LAYOUTVERSION = 202, ATTRIBUTEKIND_LEAF = 203, ATTRIBUTEKIND_LOCKRETURNED = 204, ATTRIBUTEKIND_LOCKSEXCLUDED = 205, ATTRIBUTEKIND_M68KINTERRUPT = 206, ATTRIBUTEKIND_MIGSERVERROUTINE = 207, ATTRIBUTEKIND_MSALLOCATOR = 208, ATTRIBUTEKIND_MSCONSTEXPR = 209, ATTRIBUTEKIND_MSINHERITANCE = 210, ATTRIBUTEKIND_MSNOVTABLE = 211, ATTRIBUTEKIND_MSP430INTERRUPT = 212, ATTRIBUTEKIND_MSSTRUCT = 213, ATTRIBUTEKIND_MSVTORDISP = 214, ATTRIBUTEKIND_MAXFIELDALIGNMENT = 215, ATTRIBUTEKIND_MAYALIAS = 216, ATTRIBUTEKIND_MAYBEUNDEF = 217, ATTRIBUTEKIND_MICROMIPS = 218, ATTRIBUTEKIND_MINSIZE = 219, ATTRIBUTEKIND_MINVECTORWIDTH = 220, ATTRIBUTEKIND_MIPS16 = 221, ATTRIBUTEKIND_MIPSINTERRUPT = 222, ATTRIBUTEKIND_MIPSLONGCALL = 223, ATTRIBUTEKIND_MIPSSHORTCALL = 224, ATTRIBUTEKIND_NSCONSUMESSELF = 225, ATTRIBUTEKIND_NSERRORDOMAIN = 226, ATTRIBUTEKIND_NSRETURNSAUTORELEASED = 227, ATTRIBUTEKIND_NSRETURNSNOTRETAINED = 228, ATTRIBUTEKIND_NVPTXKERNEL = 229, ATTRIBUTEKIND_NAKED = 230, ATTRIBUTEKIND_NOALIAS = 231, ATTRIBUTEKIND_NOCOMMON = 232, ATTRIBUTEKIND_NODEBUG = 233, ATTRIBUTEKIND_NODESTROY = 234, ATTRIBUTEKIND_NODUPLICATE = 235, ATTRIBUTEKIND_NOINSTRUMENTFUNCTION = 236, ATTRIBUTEKIND_NOMICROMIPS = 237, ATTRIBUTEKIND_NOMIPS16 = 238, ATTRIBUTEKIND_NOPROFILEFUNCTION = 239, ATTRIBUTEKIND_NORANDOMIZELAYOUT = 240, ATTRIBUTEKIND_NORETURN = 241, ATTRIBUTEKIND_NOSANITIZE = 242, ATTRIBUTEKIND_NOSPECULATIVELOADHARDENING = 243, ATTRIBUTEKIND_NOSPLITSTACK = 244, ATTRIBUTEKIND_NOSTACKPROTECTOR = 245, ATTRIBUTEKIND_NOTHREADSAFETYANALYSIS = 246, ATTRIBUTEKIND_NOTHROW = 247, ATTRIBUTEKIND_NOUNIQUEADDRESS = 248, ATTRIBUTEKIND_NOUWTABLE = 249, ATTRIBUTEKIND_NOTTAILCALLED = 250, ATTRIBUTEKIND_OMPALLOCATEDECL = 251, ATTRIBUTEKIND_OMPCAPTURENOINIT = 252, ATTRIBUTEKIND_OMPDECLARETARGETDECL = 253, ATTRIBUTEKIND_OMPDECLAREVARIANT = 254, ATTRIBUTEKIND_OMPTHREADPRIVATEDECL = 255, ATTRIBUTEKIND_OSCONSUMESTHIS = 256, ATTRIBUTEKIND_OSRETURNSNOTRETAINED = 257, ATTRIBUTEKIND_OSRETURNSRETAINED = 258, ATTRIBUTEKIND_OSRETURNSRETAINEDONNONZERO = 259, ATTRIBUTEKIND_OSRETURNSRETAINEDONZERO = 260, ATTRIBUTEKIND_OBJCBRIDGE = 261, ATTRIBUTEKIND_OBJCBRIDGEMUTABLE = 262, ATTRIBUTEKIND_OBJCBRIDGERELATED = 263, ATTRIBUTEKIND_OBJCEXCEPTION = 264, ATTRIBUTEKIND_OBJCEXPLICITPROTOCOLIMPL = 265, ATTRIBUTEKIND_OBJCEXTERNALLYRETAINED = 266, ATTRIBUTEKIND_OBJCINDEPENDENTCLASS = 267, ATTRIBUTEKIND_OBJCMETHODFAMILY = 268, ATTRIBUTEKIND_OBJCNSOBJECT = 269, ATTRIBUTEKIND_OBJCPRECISELIFETIME = 270, ATTRIBUTEKIND_OBJCREQUIRESPROPERTYDEFS = 271, ATTRIBUTEKIND_OBJCREQUIRESSUPER = 272, ATTRIBUTEKIND_OBJCRETURNSINNERPOINTER = 273, ATTRIBUTEKIND_OBJCROOTCLASS = 274, ATTRIBUTEKIND_OBJCSUBCLASSINGRESTRICTED = 275, ATTRIBUTEKIND_OPENCLINTELREQDSUBGROUPSIZE = 276, ATTRIBUTEKIND_OPENCLKERNEL = 277, ATTRIBUTEKIND_OPTIMIZENONE = 278, ATTRIBUTEKIND_OVERRIDE = 279, ATTRIBUTEKIND_OWNER = 280, ATTRIBUTEKIND_OWNERSHIP = 281, ATTRIBUTEKIND_PACKED = 282, ATTRIBUTEKIND_PARAMTYPESTATE = 283, ATTRIBUTEKIND_PATCHABLEFUNCTIONENTRY = 284, ATTRIBUTEKIND_POINTER = 285, ATTRIBUTEKIND_PRAGMACLANGBSSSECTION = 286, ATTRIBUTEKIND_PRAGMACLANGDATASECTION = 287, ATTRIBUTEKIND_PRAGMACLANGRELROSECTION = 288, ATTRIBUTEKIND_PRAGMACLANGRODATASECTION = 289, ATTRIBUTEKIND_PRAGMACLANGTEXTSECTION = 290, ATTRIBUTEKIND_PREFERREDNAME = 291, ATTRIBUTEKIND_PREFERREDTYPE = 292, ATTRIBUTEKIND_PTGUARDEDBY = 293, ATTRIBUTEKIND_PTGUARDEDVAR = 294, ATTRIBUTEKIND_PURE = 295, ATTRIBUTEKIND_RISCVINTERRUPT = 296, ATTRIBUTEKIND_RANDOMIZELAYOUT = 297, ATTRIBUTEKIND_READONLYPLACEMENT = 298, ATTRIBUTEKIND_REINITIALIZES = 299, ATTRIBUTEKIND_RELEASECAPABILITY = 300, ATTRIBUTEKIND_REQDWORKGROUPSIZE = 301, ATTRIBUTEKIND_REQUIRESCAPABILITY = 302, ATTRIBUTEKIND_RESTRICT = 303, ATTRIBUTEKIND_RETAIN = 304, ATTRIBUTEKIND_RETURNTYPESTATE = 305, ATTRIBUTEKIND_RETURNSNONNULL = 306, ATTRIBUTEKIND_RETURNSTWICE = 307, ATTRIBUTEKIND_SYCLKERNEL = 308, ATTRIBUTEKIND_SYCLSPECIALCLASS = 309, ATTRIBUTEKIND_SCOPEDLOCKABLE = 310, ATTRIBUTEKIND_SECTION = 311, ATTRIBUTEKIND_SELECTANY = 312, ATTRIBUTEKIND_SENTINEL = 313, ATTRIBUTEKIND_SETTYPESTATE = 314, ATTRIBUTEKIND_SHAREDTRYLOCKFUNCTION = 315, ATTRIBUTEKIND_SPECULATIVELOADHARDENING = 316, ATTRIBUTEKIND_STANDALONEDEBUG = 317, ATTRIBUTEKIND_STRICTFP = 318, ATTRIBUTEKIND_STRICTGUARDSTACKCHECK = 319, ATTRIBUTEKIND_SWIFTASYNC = 320, ATTRIBUTEKIND_SWIFTASYNCERROR = 321, ATTRIBUTEKIND_SWIFTASYNCNAME = 322, ATTRIBUTEKIND_SWIFTATTR = 323, ATTRIBUTEKIND_SWIFTBRIDGE = 324, ATTRIBUTEKIND_SWIFTBRIDGEDTYPEDEF = 325, ATTRIBUTEKIND_SWIFTERROR = 326, ATTRIBUTEKIND_SWIFTIMPORTASNONGENERIC = 327, ATTRIBUTEKIND_SWIFTIMPORTPROPERTYASACCESSORS = 328, ATTRIBUTEKIND_SWIFTNAME = 329, ATTRIBUTEKIND_SWIFTNEWTYPE = 330, ATTRIBUTEKIND_SWIFTPRIVATE = 331, ATTRIBUTEKIND_TLSMODEL = 332, ATTRIBUTEKIND_TARGET = 333, ATTRIBUTEKIND_TARGETCLONES = 334, ATTRIBUTEKIND_TARGETVERSION = 335, ATTRIBUTEKIND_TESTTYPESTATE = 336, ATTRIBUTEKIND_TRANSPARENTUNION = 337, ATTRIBUTEKIND_TRIVIALABI = 338, ATTRIBUTEKIND_TRYACQUIRECAPABILITY = 339, ATTRIBUTEKIND_TYPETAGFORDATATYPE = 340, ATTRIBUTEKIND_TYPEVISIBILITY = 341, ATTRIBUTEKIND_UNAVAILABLE = 342, ATTRIBUTEKIND_UNINITIALIZED = 343, ATTRIBUTEKIND_UNSAFEBUFFERUSAGE = 344, ATTRIBUTEKIND_UNUSED = 345, ATTRIBUTEKIND_USED = 346, ATTRIBUTEKIND_USINGIFEXISTS = 347, ATTRIBUTEKIND_UUID = 348, ATTRIBUTEKIND_VECRETURN = 349, ATTRIBUTEKIND_VECTYPEHINT = 350, ATTRIBUTEKIND_VISIBILITY = 351, ATTRIBUTEKIND_WARNUNUSED = 352, ATTRIBUTEKIND_WARNUNUSEDRESULT = 353, ATTRIBUTEKIND_WEAK = 354, ATTRIBUTEKIND_WEAKIMPORT = 355, ATTRIBUTEKIND_WEAKREF = 356, ATTRIBUTEKIND_WEBASSEMBLYEXPORTNAME = 357, ATTRIBUTEKIND_WEBASSEMBLYIMPORTMODULE = 358, ATTRIBUTEKIND_WEBASSEMBLYIMPORTNAME = 359, ATTRIBUTEKIND_WORKGROUPSIZEHINT = 360, ATTRIBUTEKIND_X86FORCEALIGNARGPOINTER = 361, ATTRIBUTEKIND_XRAYINSTRUMENT = 362, ATTRIBUTEKIND_XRAYLOGARGS = 363, ATTRIBUTEKIND_ZEROCALLUSEDREGS = 364, ATTRIBUTEKIND_ABITAG = 365, ATTRIBUTEKIND_ALIAS = 366, ATTRIBUTEKIND_ALIGNVALUE = 367, ATTRIBUTEKIND_BUILTINALIAS = 368, ATTRIBUTEKIND_CALLEDONCE = 369, ATTRIBUTEKIND_IFUNC = 370, ATTRIBUTEKIND_INITSEG = 371, ATTRIBUTEKIND_LOADERUNINITIALIZED = 372, ATTRIBUTEKIND_LOOPHINT = 373, ATTRIBUTEKIND_MODE = 374, ATTRIBUTEKIND_NOBUILTIN = 375, ATTRIBUTEKIND_NOESCAPE = 376, ATTRIBUTEKIND_OMPCAPTUREKIND = 377, ATTRIBUTEKIND_OMPDECLARESIMDDECL = 378, ATTRIBUTEKIND_OMPREFERENCEDVAR = 379, ATTRIBUTEKIND_OBJCBOXABLE = 380, ATTRIBUTEKIND_OBJCCLASSSTUB = 381, ATTRIBUTEKIND_OBJCDESIGNATEDINITIALIZER = 382, ATTRIBUTEKIND_OBJCDIRECT = 383, ATTRIBUTEKIND_OBJCDIRECTMEMBERS = 384, ATTRIBUTEKIND_OBJCNONLAZYCLASS = 385, ATTRIBUTEKIND_OBJCNONRUNTIMEPROTOCOL = 386, ATTRIBUTEKIND_OBJCRUNTIMENAME = 387, ATTRIBUTEKIND_OBJCRUNTIMEVISIBLE = 388, ATTRIBUTEKIND_OPENCLACCESS = 389, ATTRIBUTEKIND_OVERLOADABLE = 390, ATTRIBUTEKIND_RENDERSCRIPTKERNEL = 391, ATTRIBUTEKIND_SWIFTOBJCMEMBERS = 392, ATTRIBUTEKIND_SWIFTVERSIONEDADDITION = 393, ATTRIBUTEKIND_SWIFTVERSIONEDREMOVAL = 394, ATTRIBUTEKIND_THREAD = 395, ATTRIBUTEKIND_FIRSTATTR = 396, ATTRIBUTEKIND_LASTATTR = 397, ATTRIBUTEKIND_FIRSTTYPEATTR = 398, ATTRIBUTEKIND_LASTTYPEATTR = 399, ATTRIBUTEKIND_FIRSTSTMTATTR = 400, ATTRIBUTEKIND_LASTSTMTATTR = 401, ATTRIBUTEKIND_FIRSTDECLORSTMTATTR = 402, ATTRIBUTEKIND_LASTDECLORSTMTATTR = 403, ATTRIBUTEKIND_FIRSTINHERITABLEATTR = 404, ATTRIBUTEKIND_LASTINHERITABLEATTR = 405, ATTRIBUTEKIND_FIRSTDECLORTYPEATTR = 406, ATTRIBUTEKIND_LASTDECLORTYPEATTR = 407, ATTRIBUTEKIND_FIRSTINHERITABLEPARAMATTR = 408, ATTRIBUTEKIND_LASTINHERITABLEPARAMATTR = 409, ATTRIBUTEKIND_FIRSTPARAMETERABIATTR = 410, ATTRIBUTEKIND_LASTPARAMETERABIATTR = 411, ATTRIBUTEKIND_FIRSTHLSLANNOTATIONATTR = 412, ATTRIBUTEKIND_LASTHLSLANNOTATIONATTR = 413, };
enum class FormatAttrKind : int32_t { FORMATATTRKIND_PRINTF = 0, FORMATATTRKIND_SCANF = 1, FORMATATTRKIND_STRFTIME = 2, FORMATATTRKIND_GNU_PRINTF = 3, FORMATATTRKIND_GNU_SCANF = 4, FORMATATTRKIND_GNU_STRFTIME = 5, FORMATATTRKIND_STRFMON = 6, FORMATATTRKIND_MS_PRINTF = 7, FORMATATTRKIND_MS_SCANF = 8, FORMATATTRKIND_MS_STRFTIME = 9, FORMATATTRKIND_NSSTRING = 10, };
enum class VisibilityType : int32_t { VISIBILITYTYPE_DEFAULT = 0, VISIBILITYTYPE_HIDDEN = 1, VISIBILITYTYPE_PROTECTED = 2, };
enum class ExplicitSpecKind : int32_t { EXPLICITSPECKIND_RESOLVEDFALSE = 0, EXPLICITSPECKIND_RESOLVEDTRUE = 1, EXPLICITSPECKIND_UNRESOLVED = 2, };
enum class InitializationStyle : int32_t { INITIALIZATIONSTYLE_CINIT = 0, INITIALIZATIONSTYLE_CALL_INIT = 1, INITIALIZATIONSTYLE_LIST_INIT = 2, INITIALIZATIONSTYLE_PARENLISTINIT = 3, };
enum class LanguageId : int32_t { LANGUAGEID_C = 0, LANGUAGEID_CXX = 1, };
enum class Linkage : int32_t { LINKAGE_INVALID = 0, LINKAGE_NONE = 1, LINKAGE_INTERNAL = 2, LINKAGE_UNIQUEEXTERNAL = 3, LINKAGE_VISIBLENONE = 4, LINKAGE_MODULE = 5, LINKAGE_EXTERNAL = 6, };
enum class NameKind : int32_t { NAMEKIND_IDENTIFIER = 0, NAMEKIND_OBJ_C_ZERO_ARG_SELECTOR = 1, NAMEKIND_OBJ_C_ONE_ARG_SELECTOR = 2, NAMEKIND_OBJ_C_MULTI_ARG_SELECTOR = 3, NAMEKIND_CXX_CONSTRUCTOR_NAME = 4, NAMEKIND_CXX_DESTRUCTOR_NAME = 5, NAMEKIND_CXX_CONVERSION_FUNCTION_NAME = 6, NAMEKIND_CXX_DEDUCTION_GUIDE_NAME = 7, NAMEKIND_CXX_OPERATOR_NAME = 8, NAMEKIND_CXX_LITERAL_OPERATOR_NAME = 9, NAMEKIND_CXX_USING_DIRECTIVE = 10, };
enum class StorageClass : int32_t { STORAGECLASS_NONE = 0, STORAGECLASS_EXTERN = 1, STORAGECLASS_STATIC = 2, STORAGECLASS_PRIVATEEXTERN = 3, STORAGECLASS_AUTO = 4, STORAGECLASS_REGISTER = 5, };
enum class TemplateKind : int32_t { TEMPLATEKIND_NON_TEMPLATE = 0, TEMPLATEKIND_FUNCTION_TEMPLATE = 1, TEMPLATEKIND_MEMBER_SPECIALIZATION = 2, TEMPLATEKIND_FUNCTION_TEMPLATE_SPECIALIZATION = 3, TEMPLATEKIND_DEPENDENT_FUNCTION_TEMPLATE_SPECIALIZATION = 4, };
enum class TemplateSpecializationKind : int32_t { TEMPLATESPECIALIZATIONKIND_UNDECLARED = 0, TEMPLATESPECIALIZATIONKIND_IMPLICITINSTANTIATION = 1, TEMPLATESPECIALIZATIONKIND_EXPLICITSPECIALIZATION = 2, TEMPLATESPECIALIZATIONKIND_EXPLICITINSTANTIATIONDECLARATION = 3, TEMPLATESPECIALIZATIONKIND_EXPLICITINSTANTIATIONDEFINITION = 4, };
enum class Visibility : int32_t { VISIBILITY_HIDDEN = 0, VISIBILITY_PROTECTED = 1, VISIBILITY_DEFAULT = 2, };
enum class BinaryOperatorKind : int32_t { BINARYOPERATORKIND_PTRMEMD = 0, BINARYOPERATORKIND_PTRMEMI = 1, BINARYOPERATORKIND_MUL = 2, BINARYOPERATORKIND_DIV = 3, BINARYOPERATORKIND_REM = 4, BINARYOPERATORKIND_ADD = 5, BINARYOPERATORKIND_SUB = 6, BINARYOPERATORKIND_SHL = 7, BINARYOPERATORKIND_SHR = 8, BINARYOPERATORKIND_CMP = 9, BINARYOPERATORKIND_LT = 10, BINARYOPERATORKIND_GT = 11, BINARYOPERATORKIND_LE = 12, BINARYOPERATORKIND_GE = 13, BINARYOPERATORKIND_EQ = 14, BINARYOPERATORKIND_NE = 15, BINARYOPERATORKIND_AND = 16, BINARYOPERATORKIND_XOR = 17, BINARYOPERATORKIND_OR = 18, BINARYOPERATORKIND_LAND = 19, BINARYOPERATORKIND_LOR = 20, BINARYOPERATORKIND_ASSIGN = 21, BINARYOPERATORKIND_MULASSIGN = 22, BINARYOPERATORKIND_DIVASSIGN = 23, BINARYOPERATORKIND_REMASSIGN = 24, BINARYOPERATORKIND_ADDASSIGN = 25, BINARYOPERATORKIND_SUBASSIGN = 26, BINARYOPERATORKIND_SHLASSIGN = 27, BINARYOPERATORKIND_SHRASSIGN = 28, BINARYOPERATORKIND_ANDASSIGN = 29, BINARYOPERATORKIND_XORASSIGN = 30, BINARYOPERATORKIND_ORASSIGN = 31, BINARYOPERATORKIND_COMMA = 32, };
enum class CharacterKind : int32_t { CHARACTERKIND_ASCII = 0, CHARACTERKIND_WIDE = 1, CHARACTERKIND_UTF8 = 2, CHARACTERKIND_UTF16 = 3, CHARACTERKIND_UTF32 = 4, };
enum class ConstructionKind : int32_t { CONSTRUCTIONKIND_COMPLETE = 0, CONSTRUCTIONKIND_NONVIRTUALBASE = 1, CONSTRUCTIONKIND_VIRTUALBASE = 2, CONSTRUCTIONKIND_DELEGATING = 3, };
enum class LambdaCaptureDefault : int32_t { LAMBDACAPTUREDEFAULT_NONE = 0, LAMBDACAPTUREDEFAULT_BYCOPY = 1, LAMBDACAPTUREDEFAULT_BYREF = 2, };
enum class LambdaCaptureKind : int32_t { LAMBDACAPTUREKIND_THIS = 0, LAMBDACAPTUREKIND_STARTHIS = 1, LAMBDACAPTUREKIND_BYCOPY = 2, LAMBDACAPTUREKIND_BYREF = 3, LAMBDACAPTUREKIND_VLATYPE = 4, };
enum class NewInitStyle : int32_t { NEWINITSTYLE_NO_INIT = 0, NEWINITSTYLE_CALL_INIT = 1, NEWINITSTYLE_LIST_INIT = 2, };
enum class ObjectKind : int32_t { OBJECTKIND_ORDINARY = 0, OBJECTKIND_BIT_FIELD = 1, OBJECTKIND_OBJ_C_PROPERTY = 2, OBJECTKIND_OBJ_C_SUBSCRIPT = 3, OBJECTKIND_VECTOR_COMPONENT = 4, };
enum class PredefinedIdType : int32_t { PREDEFINEDIDTYPE_FUNC = 0, PREDEFINEDIDTYPE_FUNCTION = 1, PREDEFINEDIDTYPE_LFUNCTION = 2, PREDEFINEDIDTYPE_FUNCDNAME = 3, PREDEFINEDIDTYPE_FUNCSIG = 4, PREDEFINEDIDTYPE_LFUNCSIG = 5, PREDEFINEDIDTYPE_PRETTYFUNCTION = 6, PREDEFINEDIDTYPE_PRETTYFUNCTIONNOVIRTUAL = 7, };
enum class StringKind : int32_t { STRINGKIND_ORDINARY = 0, STRINGKIND_WIDE = 1, STRINGKIND_UTF8 = 2, STRINGKIND_UTF16 = 3, STRINGKIND_UTF32 = 4, STRINGKIND_UNEVALUATED = 5, };
enum class UnaryOperatorKind : int32_t { UNARYOPERATORKIND_POSTINC = 0, UNARYOPERATORKIND_POSTDEC = 1, UNARYOPERATORKIND_PREINC = 2, UNARYOPERATORKIND_PREDEC = 3, UNARYOPERATORKIND_ADDROF = 4, UNARYOPERATORKIND_DEREF = 5, UNARYOPERATORKIND_PLUS = 6, UNARYOPERATORKIND_MINUS = 7, UNARYOPERATORKIND_NOT = 8, UNARYOPERATORKIND_LNOT = 9, UNARYOPERATORKIND_REAL = 10, UNARYOPERATORKIND_IMAG = 11, UNARYOPERATORKIND_EXTENSION = 12, UNARYOPERATORKIND_COAWAIT = 13, };
enum class UnaryOperatorPosition : int32_t { UNARYOPERATORPOSITION_PREFIX = 0, UNARYOPERATORPOSITION_POSTFIX = 1, };
enum class ValueKind : int32_t { VALUEKIND_R_VALUE = 0, VALUEKIND_L_VALUE = 1, VALUEKIND_X_VALUE = 2, };
enum class AddressSpaceQualifierV2 : int32_t { ADDRESSSPACEQUALIFIERV2_NONE = 0, ADDRESSSPACEQUALIFIERV2_GLOBAL = 1, ADDRESSSPACEQUALIFIERV2_LOCAL = 2, ADDRESSSPACEQUALIFIERV2_CONSTANT = 3, ADDRESSSPACEQUALIFIERV2_GENERIC = 4, ADDRESSSPACEQUALIFIERV2_DEFAULT = 5, ADDRESSSPACEQUALIFIERV2_PRIVATE = 6, ADDRESSSPACEQUALIFIERV2_CUDA_CONSTANT = 7, ADDRESSSPACEQUALIFIERV2_CUDA_DEVICE = 8, ADDRESSSPACEQUALIFIERV2_CUDA_SHARED = 9, };
enum class ArraySizeModifier : int32_t { ARRAYSIZEMODIFIER_NORMAL = 0, ARRAYSIZEMODIFIER_STATIC = 1, ARRAYSIZEMODIFIER_STAR = 2, };
enum class BuiltinKind : int32_t { BUILTINKIND_OCLIMAGE1DRO = 0, BUILTINKIND_OCLIMAGE1DARRAYRO = 1, BUILTINKIND_OCLIMAGE1DBUFFERRO = 2, BUILTINKIND_OCLIMAGE2DRO = 3, BUILTINKIND_OCLIMAGE2DARRAYRO = 4, BUILTINKIND_OCLIMAGE2DDEPTHRO = 5, BUILTINKIND_OCLIMAGE2DARRAYDEPTHRO = 6, BUILTINKIND_OCLIMAGE2DMSAARO = 7, BUILTINKIND_OCLIMAGE2DARRAYMSAARO = 8, BUILTINKIND_OCLIMAGE2DMSAADEPTHRO = 9, BUILTINKIND_OCLIMAGE2DARRAYMSAADEPTHRO = 10, BUILTINKIND_OCLIMAGE3DRO = 11, BUILTINKIND_OCLIMAGE1DWO = 12, BUILTINKIND_OCLIMAGE1DARRAYWO = 13, BUILTINKIND_OCLIMAGE1DBUFFERWO = 14, BUILTINKIND_OCLIMAGE2DWO = 15, BUILTINKIND_OCLIMAGE2DARRAYWO = 16, BUILTINKIND_OCLIMAGE2DDEPTHWO = 17, BUILTINKIND_OCLIMAGE2DARRAYDEPTHWO = 18, BUILTINKIND_OCLIMAGE2DMSAAWO = 19, BUILTINKIND_OCLIMAGE2DARRAYMSAAWO = 20, BUILTINKIND_OCLIMAGE2DMSAADEPTHWO = 21, BUILTINKIND_OCLIMAGE2DARRAYMSAADEPTHWO = 22, BUILTINKIND_OCLIMAGE3DWO = 23, BUILTINKIND_OCLIMAGE1DRW = 24, BUILTINKIND_OCLIMAGE1DARRAYRW = 25, BUILTINKIND_OCLIMAGE1DBUFFERRW = 26, BUILTINKIND_OCLIMAGE2DRW = 27, BUILTINKIND_OCLIMAGE2DARRAYRW = 28, BUILTINKIND_OCLIMAGE2DDEPTHRW = 29, BUILTINKIND_OCLIMAGE2DARRAYDEPTHRW = 30, BUILTINKIND_OCLIMAGE2DMSAARW = 31, BUILTINKIND_OCLIMAGE2DARRAYMSAARW = 32, BUILTINKIND_OCLIMAGE2DMSAADEPTHRW = 33, BUILTINKIND_OCLIMAGE2DARRAYMSAADEPTHRW = 34, BUILTINKIND_OCLIMAGE3DRW = 35, BUILTINKIND_OCLINTELSUBGROUPAVCMCEPAYLOAD = 36, BUILTINKIND_OCLINTELSUBGROUPAVCIMEPAYLOAD = 37, BUILTINKIND_OCLINTELSUBGROUPAVCREFPAYLOAD = 38, BUILTINKIND_OCLINTELSUBGROUPAVCSICPAYLOAD = 39, BUILTINKIND_OCLINTELSUBGROUPAVCMCERESULT = 40, BUILTINKIND_OCLINTELSUBGROUPAVCIMERESULT = 41, BUILTINKIND_OCLINTELSUBGROUPAVCREFRESULT = 42, BUILTINKIND_OCLINTELSUBGROUPAVCSICRESULT = 43, BUILTINKIND_OCLINTELSUBGROUPAVCIMERESULTSINGLEREFSTREAMOUT = 44, BUILTINKIND_OCLINTELSUBGROUPAVCIMERESULTDUALREFSTREAMOUT = 45, BUILTINKIND_OCLINTELSUBGROUPAVCIMESINGLEREFSTREAMIN = 46, BUILTINKIND_OCLINTELSUBGROUPAVCIMEDUALREFSTREAMIN = 47, BUILTINKIND_SVEINT8 = 48, BUILTINKIND_SVEINT16 = 49, BUILTINKIND_SVEINT32 = 50, BUILTINKIND_SVEINT64 = 51, BUILTINKIND_SVEUINT8 = 52, BUILTINKIND_SVEUINT16 = 53, BUILTINKIND_SVEUINT32 = 54, BUILTINKIND_SVEUINT64 = 55, BUILTINKIND_SVEFLOAT16 = 56, BUILTINKIND_SVEFLOAT32 = 57, BUILTINKIND_SVEFLOAT64 = 58, BUILTINKIND_SVEBFLOAT16 = 59, BUILTINKIND_SVEINT8X2 = 60, BUILTINKIND_SVEINT16X2 = 61, BUILTINKIND_SVEINT32X2 = 62, BUILTINKIND_SVEINT64X2 = 63, BUILTINKIND_SVEUINT8X2 = 64, BUILTINKIND_SVEUINT16X2 = 65, BUILTINKIND_SVEUINT32X2 = 66, BUILTINKIND_SVEUINT64X2 = 67, BUILTINKIND_SVEFLOAT16X2 = 68, BUILTINKIND_SVEFLOAT32X2 = 69, BUILTINKIND_SVEFLOAT64X2 = 70, BUILTINKIND_SVEBFLOAT16X2 = 71, BUILTINKIND_SVEINT8X3 = 72, BUILTINKIND_SVEINT16X3 = 73, BUILTINKIND_SVEINT32X3 = 74, BUILTINKIND_SVEINT64X3 = 75, BUILTINKIND_SVEUINT8X3 = 76, BUILTINKIND_SVEUINT16X3 = 77, BUILTINKIND_SVEUINT32X3 = 78, BUILTINKIND_SVEUINT64X3 = 79, BUILTINKIND_SVEFLOAT16X3 = 80, BUILTINKIND_SVEFLOAT32X3 = 81, BUILTINKIND_SVEFLOAT64X3 = 82, BUILTINKIND_SVEBFLOAT16X3 = 83, BUILTINKIND_SVEINT8X4 = 84, BUILTINKIND_SVEINT16X4 = 85, BUILTINKIND_SVEINT32X4 = 86, BUILTINKIND_SVEINT64X4 = 87, BUILTINKIND_SVEUINT8X4 = 88, BUILTINKIND_SVEUINT16X4 = 89, BUILTINKIND_SVEUINT32X4 = 90, BUILTINKIND_SVEUINT64X4 = 91, BUILTINKIND_SVEFLOAT16X4 = 92, BUILTINKIND_SVEFLOAT32X4 = 93, BUILTINKIND_SVEFLOAT64X4 = 94, BUILTINKIND_SVEBFLOAT16X4 = 95, BUILTINKIND_SVEBOOL = 96, BUILTINKIND_VECTORQUAD = 97, BUILTINKIND_VECTORPAIR = 98, BUILTINKIND_RVVINT8MF8 = 99, BUILTINKIND_RVVINT8MF4 = 100, BUILTINKIND_RVVINT8MF2 = 101, BUILTINKIND_RVVINT8M1 = 102, BUILTINKIND_RVVINT8M2 = 103, BUILTINKIND_RVVINT8M4 = 104, BUILTINKIND_RVVINT8M8 = 105, BUILTINKIND_RVVUINT8MF8 = 106, BUILTINKIND_RVVUINT8MF4 = 107, BUILTINKIND_RVVUINT8MF2 = 108, BUILTINKIND_RVVUINT8M1 = 109, BUILTINKIND_RVVUINT8M2 = 110, BUILTINKIND_RVVUINT8M4 = 111, BUILTINKIND_RVVUINT8M8 = 112, BUILTINKIND_RVVINT16MF4 = 113, BUILTINKIND_RVVINT16MF2 = 114, BUILTINKIND_RVVINT16M1 = 115, BUILTINKIND_RVVINT16M2 = 116, BUILTINKIND_RVVINT16M4 = 117, BUILTINKIND_RVVINT16M8 = 118, BUILTINKIND_RVVUINT16MF4 = 119, BUILTINKIND_RVVUINT16MF2 = 120, BUILTINKIND_RVVUINT16M1 = 121, BUILTINKIND_RVVUINT16M2 = 122, BUILTINKIND_RVVUINT16M4 = 123, BUILTINKIND_RVVUINT16M8 = 124, BUILTINKIND_RVVINT32MF2 = 125, BUILTINKIND_RVVINT32M1 = 126, BUILTINKIND_RVVINT32M2 = 127, BUILTINKIND_RVVINT32M4 = 128, BUILTINKIND_RVVINT32M8 = 129, BUILTINKIND_RVVUINT32MF2 = 130, BUILTINKIND_RVVUINT32M1 = 131, BUILTINKIND_RVVUINT32M2 = 132, BUILTINKIND_RVVUINT32M4 = 133, BUILTINKIND_RVVUINT32M8 = 134, BUILTINKIND_RVVINT64M1 = 135, BUILTINKIND_RVVINT64M2 = 136, BUILTINKIND_RVVINT64M4 = 137, BUILTINKIND_RVVINT64M8 = 138, BUILTINKIND_RVVUINT64M1 = 139, BUILTINKIND_RVVUINT64M2 = 140, BUILTINKIND_RVVUINT64M4 = 141, BUILTINKIND_RVVUINT64M8 = 142, BUILTINKIND_RVVFLOAT16MF4 = 143, BUILTINKIND_RVVFLOAT16MF2 = 144, BUILTINKIND_RVVFLOAT16M1 = 145, BUILTINKIND_RVVFLOAT16M2 = 146, BUILTINKIND_RVVFLOAT16M4 = 147, BUILTINKIND_RVVFLOAT16M8 = 148, BUILTINKIND_RVVFLOAT32MF2 = 149, BUILTINKIND_RVVFLOAT32M1 = 150, BUILTINKIND_RVVFLOAT32M2 = 151, BUILTINKIND_RVVFLOAT32M4 = 152, BUILTINKIND_RVVFLOAT32M8 = 153, BUILTINKIND_RVVFLOAT64M1 = 154, BUILTINKIND_RVVFLOAT64M2 = 155, BUILTINKIND_RVVFLOAT64M4 = 156, BUILTINKIND_RVVFLOAT64M8 = 157, BUILTINKIND_RVVBOOL1 = 158, BUILTINKIND_RVVBOOL2 = 159, BUILTINKIND_RVVBOOL4 = 160, BUILTINKIND_RVVBOOL8 = 161, BUILTINKIND_RVVBOOL16 = 162, BUILTINKIND_RVVBOOL32 = 163, BUILTINKIND_RVVBOOL64 = 164, BUILTINKIND_VOID = 165, BUILTINKIND_BOOL = 166, BUILTINKIND_CHAR_U = 167, BUILTINKIND_UCHAR = 168, BUILTINKIND_WCHAR_U = 169, BUILTINKIND_CHAR8 = 170, BUILTINKIND_CHAR16 = 171, BUILTINKIND_CHAR32 = 172, BUILTINKIND_USHORT = 173, BUILTINKIND_UINT = 174, BUILTINKIND_ULONG = 175, BUILTINKIND_ULONGLONG = 176, BUILTINKIND_UINT128 = 177, BUILTINKIND_CHAR_S = 178, BUILTINKIND_SCHAR = 179, BUILTINKIND_WCHAR_S = 180, BUILTINKIND_SHORT = 181, BUILTINKIND_INT = 182, BUILTINKIND_LONG = 183, BUILTINKIND_LONGLONG = 184, BUILTINKIND_INT128 = 185, BUILTINKIND_SHORTACCUM = 186, BUILTINKIND_ACCUM = 187, BUILTINKIND_LONGACCUM = 188, BUILTINKIND_USHORTACCUM = 189, BUILTINKIND_UACCUM = 190, BUILTINKIND_ULONGACCUM = 191, BUILTINKIND_SHORTFRACT = 192, BUILTINKIND_FRACT = 193, BUILTINKIND_LONGFRACT = 194, BUILTINKIND_USHORTFRACT = 195, BUILTINKIND_UFRACT = 196, BUILTINKIND_ULONGFRACT = 197, BUILTINKIND_SATSHORTACCUM = 198, BUILTINKIND_SATACCUM = 199, BUILTINKIND_SATLONGACCUM = 200, BUILTINKIND_SATUSHORTACCUM = 201, BUILTINKIND_SATUACCUM = 202, BUILTINKIND_SATULONGACCUM = 203, BUILTINKIND_SATSHORTFRACT = 204, BUILTINKIND_SATFRACT = 205, BUILTINKIND_SATLONGFRACT = 206, BUILTINKIND_SATUSHORTFRACT = 207, BUILTINKIND_SATUFRACT = 208, BUILTINKIND_SATULONGFRACT = 209, BUILTINKIND_HALF = 210, BUILTINKIND_FLOAT = 211, BUILTINKIND_DOUBLE = 212, BUILTINKIND_LONGDOUBLE = 213, BUILTINKIND_FLOAT16 = 214, BUILTINKIND_BFLOAT16 = 215, BUILTINKIND_FLOAT128 = 216, BUILTINKIND_IBM128 = 217, BUILTINKIND_NULLPTR = 218, BUILTINKIND_OBJCID = 219, BUILTINKIND_OBJCCLASS = 220, BUILTINKIND_OBJCSEL = 221, BUILTINKIND_OCLSAMPLER = 222, BUILTINKIND_OCLEVENT = 223, BUILTINKIND_OCLCLKEVENT = 224, BUILTINKIND_OCLQUEUE = 225, BUILTINKIND_OCLRESERVEID = 226, BUILTINKIND_DEPENDENT = 227, BUILTINKIND_OVERLOAD = 228, BUILTINKIND_BOUNDMEMBER = 229, BUILTINKIND_PSEUDOOBJECT = 230, BUILTINKIND_UNKNOWNANY = 231, BUILTINKIND_BUILTINFN = 232, BUILTINKIND_ARCUNBRIDGEDCAST = 233, BUILTINKIND_INCOMPLETEMATRIXIDX = 234, BUILTINKIND_OMPARRAYSECTION = 235, BUILTINKIND_OMPARRAYSHAPING = 236, BUILTINKIND_OMPITERATOR = 237, };
enum class C99Qualifier : int32_t { C99QUALIFIER_CONST = 0, C99QUALIFIER_RESTRICT = 1, C99QUALIFIER_RESTRICT_C99 = 2, C99QUALIFIER_VOLATILE = 3, };
enum class CallingConvention : int32_t { CALLINGCONVENTION_C = 0, CALLINGCONVENTION_X86STDCALL = 1, CALLINGCONVENTION_X86FASTCALL = 2, CALLINGCONVENTION_X86THISCALL = 3, CALLINGCONVENTION_X86VECTORCALL = 4, CALLINGCONVENTION_X86PASCAL = 5, CALLINGCONVENTION_WIN64 = 6, CALLINGCONVENTION_X86_64SYSV = 7, CALLINGCONVENTION_X86REGCALL = 8, CALLINGCONVENTION_AAPCS = 9, CALLINGCONVENTION_AAPCS_VFP = 10, CALLINGCONVENTION_INTELOCLBICC = 11, CALLINGCONVENTION_SPIRFUNCTION = 12, CALLINGCONVENTION_OPENCLKERNEL = 13, CALLINGCONVENTION_SWIFT = 14, CALLINGCONVENTION_SWIFTASYNC = 15, CALLINGCONVENTION_PRESERVEMOST = 16, CALLINGCONVENTION_PRESERVEALL = 17, CALLINGCONVENTION_AARCH64VECTORCALL = 18, CALLINGCONVENTION_AARCH64SVEPCS = 19, CALLINGCONVENTION_AMDGPUKERNELCALL = 20, CALLINGCONVENTION_M68KRTD = 21, };
enum class ElaboratedTypeKeyword : int32_t { ELABORATEDTYPEKEYWORD_STRUCT = 0, ELABORATEDTYPEKEYWORD_INTERFACE = 1, ELABORATEDTYPEKEYWORD_UNION = 2, ELABORATEDTYPEKEYWORD_CLASS = 3, ELABORATEDTYPEKEYWORD_ENUM = 4, ELABORATEDTYPEKEYWORD_TYPENAME = 5, ELABORATEDTYPEKEYWORD_NONE = 6, };
enum class ExceptionSpecificationType : int32_t { EXCEPTIONSPECIFICATIONTYPE_NONE = 0, EXCEPTIONSPECIFICATIONTYPE_DYNAMICNONE = 1, EXCEPTIONSPECIFICATIONTYPE_DYNAMIC = 2, EXCEPTIONSPECIFICATIONTYPE_MSANY = 3, EXCEPTIONSPECIFICATIONTYPE_NOTHROW = 4, EXCEPTIONSPECIFICATIONTYPE_BASICNOEXCEPT = 5, EXCEPTIONSPECIFICATIONTYPE_DEPENDENTNOEXCEPT = 6, EXCEPTIONSPECIFICATIONTYPE_NOEXCEPTFALSE = 7, EXCEPTIONSPECIFICATIONTYPE_NOEXCEPTTRUE = 8, EXCEPTIONSPECIFICATIONTYPE_UNEVALUATED = 9, EXCEPTIONSPECIFICATIONTYPE_UNINSTANTIATED = 10, EXCEPTIONSPECIFICATIONTYPE_UNPARSED = 11, };
enum class TypeDependency : int32_t { TYPEDEPENDENCY_DEPENDENT = 0, TYPEDEPENDENCY_INSTANTIATION_DEPENDENT = 1, TYPEDEPENDENCY_NONE = 2, };
enum class UnaryTransformTypeKind : int32_t { UNARYTRANSFORMTYPEKIND_ADDLVALUEREFERENCE = 0, UNARYTRANSFORMTYPEKIND_ADDPOINTER = 1, UNARYTRANSFORMTYPEKIND_ADDRVALUEREFERENCE = 2, UNARYTRANSFORMTYPEKIND_DECAY = 3, UNARYTRANSFORMTYPEKIND_MAKESIGNED = 4, UNARYTRANSFORMTYPEKIND_MAKEUNSIGNED = 5, UNARYTRANSFORMTYPEKIND_REMOVEALLEXTENTS = 6, UNARYTRANSFORMTYPEKIND_REMOVECONST = 7, UNARYTRANSFORMTYPEKIND_REMOVECV = 8, UNARYTRANSFORMTYPEKIND_REMOVECVREF = 9, UNARYTRANSFORMTYPEKIND_REMOVEEXTENT = 10, UNARYTRANSFORMTYPEKIND_REMOVEPOINTER = 11, UNARYTRANSFORMTYPEKIND_REMOVEREFERENCE = 12, UNARYTRANSFORMTYPEKIND_REMOVERESTRICT = 13, UNARYTRANSFORMTYPEKIND_REMOVEVOLATILE = 14, UNARYTRANSFORMTYPEKIND_ENUMUNDERLYINGTYPE = 15, };
enum class AccessSpecifier : int32_t { ACCESSSPECIFIER_PUBLIC = 0, ACCESSSPECIFIER_PROTECTED = 1, ACCESSSPECIFIER_PRIVATE = 2, ACCESSSPECIFIER_NONE = 3, };
enum class CastKind : int32_t { CASTKIND_DEPENDENT = 0, CASTKIND_BITCAST = 1, CASTKIND_LVALUEBITCAST = 2, CASTKIND_LVALUETORVALUEBITCAST = 3, CASTKIND_LVALUETORVALUE = 4, CASTKIND_NOOP = 5, CASTKIND_BASETODERIVED = 6, CASTKIND_DERIVEDTOBASE = 7, CASTKIND_UNCHECKEDDERIVEDTOBASE = 8, CASTKIND_DYNAMIC = 9, CASTKIND_TOUNION = 10, CASTKIND_ARRAYTOPOINTERDECAY = 11, CASTKIND_FUNCTIONTOPOINTERDECAY = 12, CASTKIND_NULLTOPOINTER = 13, CASTKIND_NULLTOMEMBERPOINTER = 14, CASTKIND_BASETODERIVEDMEMBERPOINTER = 15, CASTKIND_DERIVEDTOBASEMEMBERPOINTER = 16, CASTKIND_MEMBERPOINTERTOBOOLEAN = 17, CASTKIND_REINTERPRETMEMBERPOINTER = 18, CASTKIND_USERDEFINEDCONVERSION = 19, CASTKIND_CONSTRUCTORCONVERSION = 20, CASTKIND_INTEGRALTOPOINTER = 21, CASTKIND_POINTERTOINTEGRAL = 22, CASTKIND_POINTERTOBOOLEAN = 23, CASTKIND_TOVOID = 24, CASTKIND_MATRIXCAST = 25, CASTKIND_VECTORSPLAT = 26, CASTKIND_INTEGRALCAST = 27, CASTKIND_INTEGRALTOBOOLEAN = 28, CASTKIND_INTEGRALTOFLOATING = 29, CASTKIND_FLOATINGTOFIXEDPOINT = 30, CASTKIND_FIXEDPOINTTOFLOATING = 31, CASTKIND_FIXEDPOINTCAST = 32, CASTKIND_FIXEDPOINTTOINTEGRAL = 33, CASTKIND_INTEGRALTOFIXEDPOINT = 34, CASTKIND_FIXEDPOINTTOBOOLEAN = 35, CASTKIND_FLOATINGTOINTEGRAL = 36, CASTKIND_FLOATINGTOBOOLEAN = 37, CASTKIND_BOOLEANTOSIGNEDINTEGRAL = 38, CASTKIND_FLOATINGCAST = 39, CASTKIND_CPOINTERTOOBJCPOINTERCAST = 40, CASTKIND_BLOCKPOINTERTOOBJCPOINTERCAST = 41, CASTKIND_ANYPOINTERTOBLOCKPOINTERCAST = 42, CASTKIND_OBJCOBJECTLVALUECAST = 43, CASTKIND_FLOATINGREALTOCOMPLEX = 44, CASTKIND_FLOATINGCOMPLEXTOREAL = 45, CASTKIND_FLOATINGCOMPLEXTOBOOLEAN = 46, CASTKIND_FLOATINGCOMPLEXCAST = 47, CASTKIND_FLOATINGCOMPLEXTOINTEGRALCOMPLEX = 48, CASTKIND_INTEGRALREALTOCOMPLEX = 49, CASTKIND_INTEGRALCOMPLEXTOREAL = 50, CASTKIND_INTEGRALCOMPLEXTOBOOLEAN = 51, CASTKIND_INTEGRALCOMPLEXCAST = 52, CASTKIND_INTEGRALCOMPLEXTOFLOATINGCOMPLEX = 53, CASTKIND_ARCPRODUCEOBJECT = 54, CASTKIND_ARCCONSUMEOBJECT = 55, CASTKIND_ARCRECLAIMRETURNEDOBJECT = 56, CASTKIND_ARCEXTENDBLOCKOBJECT = 57, CASTKIND_ATOMICTONONATOMIC = 58, CASTKIND_NONATOMICTOATOMIC = 59, CASTKIND_COPYANDAUTORELEASEBLOCKOBJECT = 60, CASTKIND_BUILTINFNTOFNPTR = 61, CASTKIND_ZEROTOOCLOPAQUETYPE = 62, CASTKIND_ADDRESSSPACECONVERSION = 63, CASTKIND_INTTOOCLSAMPLER = 64, };
enum class ReferenceQualifier : int32_t { REFERENCEQUALIFIER_LVALUE = 0, REFERENCEQUALIFIER_RVALUE = 1, REFERENCEQUALIFIER_NONE = 2, };
enum class TLSKind : int32_t { TLSKIND_NONE = 0, TLSKIND_STATIC = 1, TLSKIND_DYNAMIC = 2, };
enum class TagKind : int32_t { TAGKIND_STRUCT = 0, TAGKIND_INTERFACE = 1, TAGKIND_UNION = 2, TAGKIND_CLASS = 3, TAGKIND_ENUM = 4, TAGKIND_NO_KIND = 5, };
enum class TemplateTypeParmKind : int32_t { TEMPLATETYPEPARMKIND_TYPENAME = 0, TEMPLATETYPEPARMKIND_CLASS = 1, };
enum class UnaryExprOrTypeTrait : int32_t { UNARYEXPRORTYPETRAIT_SIZEOF = 0, UNARYEXPRORTYPETRAIT_ALIGNOF = 1, UNARYEXPRORTYPETRAIT_PREFERREDALIGNOF = 2, UNARYEXPRORTYPETRAIT_VECSTEP = 3, UNARYEXPRORTYPETRAIT_OPENMPREQUIREDSIMDALIGN = 4, };
enum class EnumScopeType : int32_t { ENUMSCOPETYPE_CLASS = 0, ENUMSCOPETYPE_STRUCT = 1, ENUMSCOPETYPE_NO_SCOPE = 2, };

struct RangeT {
  uint32_t file{};
  uint32_t line{};
  uint32_t column{};
  uint32_t end_file{};
  uint32_t end_line{};
  uint32_t end_column{};
};

struct SourceInfoT {
  std::unique_ptr<RangeT> expansion{};
  bool is_macro{};
  std::unique_ptr<RangeT> spelling{};
  bool system_header{};
};

struct NodeDataT {
  std::unique_ptr<SourceInfoT> source{};
};

struct CXXBaseSpecifierT {
  bool is_virtual{};
  bool is_pack_expansion{};
  AccessSpecifier access_specifier_as_written{};
  AccessSpecifier access_specifier_semantic{};
  int64_t type{};
};

struct ExplicitSpecifierT {
  ExplicitSpecKind kind{};
  int64_t expr{};
  bool is_specified{};
};

struct TemplateDeclarationT {
  int64_t decl{};
};

struct TemplateNullPtrT {
  int64_t type{};
};

struct TemplateTypeT {
  int64_t type{};
};

struct TemplateExpressionT {
  int64_t expr{};
};

struct TemplatePackT {
  std::vector<std::unique_ptr<TemplateArgumentT>> arguments{};
};

struct TemplateIntegralT {
  std::string integral{};
};

struct TemplateExpansionT {
  uint32_t num_expansions{};
  std::unique_ptr<TemplateNameT> template_name{};
};

struct TemplateStructuralValueT {
  int64_t type{};
};

struct TemplateArgumentT {
  UnionValue value;
};

struct DirectTemplateNameT {
  int64_t template_decl{};
};

struct QualifiedTemplateNameT {
  std::string qualifier{};
  bool has_template_keyword{};
  int64_t template_decl{};
};

struct SubstitutedTemplateNameT {
  int64_t parameter{};
  std::unique_ptr<TemplateNameT> replacement{};
};

struct UsingTemplateNameT {
  int64_t using_shadow_decl{};
};

struct DependentTemplateNameT {
  std::string qualifier{};
  std::string name{};
};

struct TemplateNameT {
  UnionValue value;
};

struct AnyMemberInitializerT {
  int64_t any_member_decl{};
};

struct BaseInitializerT {
  int64_t base_class{};
};

struct DelegatingInitializerT {
  int64_t delegated_type{};
};

struct CXXCtorInitializerT {
  int64_t init_expr{};
  bool is_in_class_member_initializer{};
  bool is_written{};
  UnionValue target;
};

struct NoExceptionDetailsT {
};

struct ComputedExceptionDetailsT {
  int64_t noexcept_expr{};
};

struct UnevaluatedExceptionDetailsT {
  int64_t source_decl{};
};

struct UninstantiatedExceptionDetailsT {
  int64_t source_decl{};
  int64_t source_template{};
};

struct ExceptionSpecificationT {
  ExceptionSpecificationType kind{};
  std::vector<int64_t> exception_types{};
  UnionValue details;
};

struct OffsetArrayT {
  int64_t expr{};
};

struct OffsetFieldT {
  std::string field_name{};
};

struct OffsetIdentifierT {
  std::string field_name{};
};

struct OffsetBaseT {
  int64_t type{};
};

struct OffsetOfComponentT {
  UnionValue value;
};

struct FieldDesignatorT {
  std::string field_name{};
};

struct ArrayDesignatorT {
  int32_t index{};
};

struct ArrayRangeDesignatorT {
  int32_t index{};
};

struct DesignatorT {
  UnionValue value;
};

struct AsmInputT {
  int64_t expr{};
  std::string constraint{};
};

struct AsmOutputT {
  int64_t expr{};
  std::string constraint{};
  bool is_plus_constraint{};
};

struct NamespaceSpecifierT {
  int64_t namespace_decl{};
};

struct NamespaceAliasSpecifierT {
  int64_t namespace_alias{};
};

struct TypeSpecifierT {
  int64_t type{};
};

struct TypeWithTemplateSpecifierT {
  int64_t type{};
};

struct GlobalSpecifierT {
};

struct SuperSpecifierT {
  int64_t super_decl{};
};

struct NestedNameSpecifierT {
  UnionValue value;
};

struct DeclDataT {
  std::unique_ptr<NodeDataT> base{};
  bool is_implicit{};
  bool is_used{};
  bool is_referenced{};
  bool is_invalid_decl{};
  bool is_module_private{};
  std::vector<int64_t> attributes{};
};

struct NamedDeclDataT {
  std::unique_ptr<DeclDataT> base{};
  std::string qualified_prefix{};
  std::string decl_name{};
  NameKind name_kind{};
  bool is_cxx_class_member{};
  bool is_cxx_instance_member{};
  Linkage linkage{};
  Visibility visibility{};
};

struct TypeDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  int64_t type_for_decl{};
};

struct TagDeclDataT {
  std::unique_ptr<TypeDeclDataT> base{};
  TagKind tag_kind{};
  bool is_complete_definition{};
};

struct RecordDeclDataT {
  std::unique_ptr<TagDeclDataT> base{};
  bool is_anonymous{};
};

struct ValueDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  int64_t type{};
  bool is_weak{};
};

struct DeclaratorDeclDataT {
  std::unique_ptr<ValueDeclDataT> base{};
};

struct TemplateDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  std::vector<int64_t> template_parameters{};
  int64_t templated_decl{};
};

struct FunctionDeclDataT {
  std::unique_ptr<DeclaratorDeclDataT> base{};
  bool is_constexpr{};
  TemplateKind template_kind{};
  StorageClass storage_class{};
  bool is_inline_specified{};
  bool is_virtual_as_written{};
  bool is_pure{};
  bool is_deleted{};
  bool is_explicitly_defaulted{};
  int64_t previous_decl{};
  int64_t canonical_decl{};
  int64_t primary_template_decl{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct CXXMethodDeclDataT {
  std::unique_ptr<FunctionDeclDataT> base{};
  int64_t record{};
  std::vector<int64_t> overridden_methods{};
  bool is_static{};
  bool is_instance{};
  bool is_const{};
  bool is_volatile{};
  bool is_virtual{};
  bool is_copy_assignment_operator{};
  bool is_move_assignment_operator{};
  int64_t this_type{};
  int64_t this_object_type{};
  bool has_inline_body{};
  bool is_lambda_static_invoker{};
};

struct CXXConstructorDeclDataT {
  std::unique_ptr<CXXMethodDeclDataT> base{};
  std::vector<std::unique_ptr<CXXCtorInitializerT>> constructor_inits{};
  bool is_default_constructor{};
  bool is_explicit{};
  std::unique_ptr<ExplicitSpecifierT> explicit_specifier{};
};

struct CXXConversionDeclDataT {
  std::unique_ptr<CXXMethodDeclDataT> base{};
  bool is_explicit{};
  bool is_lambda_to_block_pointer_conversion{};
  int64_t conversion_type{};
};

struct FieldDeclDataT {
  std::unique_ptr<DeclaratorDeclDataT> base{};
  bool is_mutable{};
};

struct ParmVarDeclDataT {
  std::unique_ptr<VarDeclDataT> base{};
  bool has_inherited_default_arg{};
};

struct VarDeclDataT {
  std::unique_ptr<ValueDeclDataT> base{};
  StorageClass storage_class{};
  TLSKind tls_kind{};
  bool is_nrvo_variable{};
  InitializationStyle init_style{};
  bool is_constexpr{};
  bool is_static_data_member{};
  bool is_out_of_line{};
  bool has_global_storage{};
};

struct TemplateTypeParmDeclDataT {
  std::unique_ptr<TypeDeclDataT> base{};
  TemplateTypeParmKind kind{};
  bool is_parameter_pack{};
  int64_t default_argument{};
};

struct UnresolvedUsingTypenameDeclDataT {
  std::unique_ptr<TypeDeclDataT> base{};
  std::string qualifier{};
  bool is_pack_expansion{};
};

struct EnumDeclDataT {
  std::unique_ptr<TagDeclDataT> base{};
  EnumScopeType enum_scope_kind{};
  int64_t integer_type{};
};

struct CXXRecordDeclDataT {
  std::unique_ptr<RecordDeclDataT> base{};
  std::vector<std::unique_ptr<CXXBaseSpecifierT>> record_bases{};
  int64_t record_definition{};
};

struct ClassTemplateSpecializationDeclDataT {
  std::unique_ptr<CXXRecordDeclDataT> base{};
  int64_t specialized_template{};
  TemplateSpecializationKind specialization_kind{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct NonTypeTemplateParmDeclDataT {
  std::unique_ptr<DeclaratorDeclDataT> base{};
  int64_t default_argument{};
  bool default_argument_was_inherited{};
  bool is_parameter_pack{};
  bool is_pack_expansion{};
  bool is_expanded_parameter_pack{};
  std::vector<int64_t> expansion_types{};
};

struct TypedefNameDeclDataT {
  std::unique_ptr<TypeDeclDataT> base{};
  int64_t underlying_type{};
};

struct AccessSpecDeclDataT {
  std::unique_ptr<DeclDataT> base{};
  AccessSpecifier access_specifier{};
};

struct UsingDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  std::unique_ptr<NestedNameSpecifierT> nested_name_specifier{};
};

struct UsingDirectiveDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  std::string qualifier{};
  int64_t namespace_{};
  int64_t namespace_as_written{};
};

struct NamespaceDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  std::string source_literal{};
};

struct NamespaceAliasDeclDataT {
  std::unique_ptr<NamedDeclDataT> base{};
  std::string nested_prefix{};
  int64_t aliased_namespace{};
};

struct LinkageSpecDeclDataT {
  std::unique_ptr<DeclDataT> base{};
  LanguageId linkage_type{};
};

struct StaticAssertDeclDataT {
  std::unique_ptr<DeclDataT> base{};
  bool is_failed{};
};

struct TemplateTemplateParmDeclDataT {
  std::unique_ptr<TemplateDeclDataT> base{};
  std::unique_ptr<TemplateArgumentT> default_argument{};
  bool is_parameter_pack{};
  bool is_pack_expansion{};
  bool is_expanded_parameter_pack{};
};

struct MSPropertyDeclDataT {
  std::unique_ptr<DeclaratorDeclDataT> base{};
  std::string getter_name{};
  std::string setter_name{};
};

struct ClassTemplatePartialSpecializationDeclDataT {
  std::unique_ptr<ClassTemplateSpecializationDeclDataT> base{};
};

struct TypeDataT {
  std::string type_as_string{};
  TypeDependency type_dependency{};
  bool is_variably_modified{};
  bool contains_unexpanded_parameter_pack{};
  bool is_from_ast{};
  int64_t unqualified_desugared_type{};
};

struct QualTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  std::vector<C99Qualifier> c99_qualifiers{};
  AddressSpaceQualifierV2 address_space_qualifier{};
  int64_t address_space{};
  int64_t unqualified_type{};
};

struct BuiltinTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  BuiltinKind kind{};
  std::string kind_literal{};
};

struct PointerTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t pointee_type{};
};

struct FunctionTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  bool is_const{};
  bool is_volatile{};
  bool is_restrict{};
  bool no_return{};
  bool produces_result{};
  bool uses_reg_parm{};
  int64_t reg_parm{};
  CallingConvention calling_convention{};
  int64_t return_type{};
};

struct FunctionProtoTypeDataT {
  std::unique_ptr<FunctionTypeDataT> base{};
  int32_t num_parameters{};
  std::vector<int64_t> parameters_types{};
  bool has_trailing_returns{};
  bool is_variadic{};
  ReferenceQualifier reference_qualifier{};
  std::unique_ptr<ExceptionSpecificationT> exception_specification{};
};

struct ArrayTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  ArraySizeModifier array_size_modifier{};
  std::vector<C99Qualifier> index_type_qualifiers{};
  int64_t element_type{};
};

struct ConstantArrayTypeDataT {
  std::unique_ptr<ArrayTypeDataT> base{};
  std::string array_size{};
};

struct VariableArrayTypeDataT {
  std::unique_ptr<ArrayTypeDataT> base{};
  int64_t size_expr{};
};

struct DependentSizedArrayTypeDataT {
  std::unique_ptr<ArrayTypeDataT> base{};
  int64_t size_expr{};
};

struct TagTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t decl{};
};

struct TypeWithKeywordDataT {
  std::unique_ptr<TypeDataT> base{};
  ElaboratedTypeKeyword elaborated_type_keyword{};
};

struct ElaboratedTypeDataT {
  std::unique_ptr<TypeWithKeywordDataT> base{};
  std::string qualifier{};
  int64_t named_type{};
};

struct TemplateTypeParmTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int32_t depth{};
  int32_t index{};
  bool is_packed{};
  int64_t decl{};
};

struct TemplateSpecializationTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  bool is_type_alias{};
  int64_t aliased_type{};
  std::string template_name{};
  int64_t template_decl{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct TypedefTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t decl{};
};

struct AdjustedTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t original_type{};
  int64_t adjusted_type{};
};

struct DecayedTypeDataT {
  std::unique_ptr<AdjustedTypeDataT> base{};
  int64_t decayed_type{};
  int64_t pointee_type{};
};

struct DecltypeTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  bool is_sugared{};
  int64_t underlying_expr{};
};

struct AutoTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t deduced_type{};
};

struct ReferenceTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t pointee_type_as_written{};
};

struct TypeOfExprTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  bool is_sugared{};
  int64_t underlying_expr{};
};

struct PackExpansionTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int32_t num_expansions{};
  int64_t pattern{};
};

struct UnaryTransformTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  UnaryTransformTypeKind kind{};
  int64_t underlying_type{};
  int64_t base_type{};
};

struct AttributedTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t modified_type{};
  int64_t equivalent_type{};
};

struct SubstTemplateTypeParmTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t replaced_parameter{};
  int64_t replacement_type{};
};

struct ComplexTypeDataT {
  std::unique_ptr<TypeDataT> base{};
  int64_t element_type{};
};

struct ExprDataT {
  std::unique_ptr<StmtDataT> base{};
  int64_t type{};
  ValueKind value_kind{};
  ObjectKind object_kind{};
  bool is_default_argument{};
};

struct CastExprDataT {
  std::unique_ptr<ExprDataT> base{};
  CastKind cast_kind{};
};

struct LiteralDataT {
  std::unique_ptr<ExprDataT> base{};
  std::string source_literal{};
};

struct CharacterLiteralDataT {
  std::unique_ptr<LiteralDataT> base{};
  int64_t value{};
  CharacterKind kind{};
};

struct IntegerLiteralDataT {
  std::unique_ptr<LiteralDataT> base{};
  std::string value{};
};

struct FloatingLiteralDataT {
  std::unique_ptr<LiteralDataT> base{};
  double value{};
};

struct StringLiteralDataT {
  std::unique_ptr<LiteralDataT> base{};
  StringKind string_kind{};
  int64_t length{};
  int32_t char_byte_width{};
  std::vector<uint32_t> string_bytes{};
};

struct CXXBoolLiteralExprDataT {
  std::unique_ptr<LiteralDataT> base{};
  bool value{};
};

struct CompoundLiteralExprDataT {
  std::unique_ptr<LiteralDataT> base{};
  bool is_file_scope{};
};

struct InitListExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int64_t array_filler{};
  bool is_explicit{};
  bool is_string_literal_init{};
  int64_t syntactic_form{};
  int64_t semantic_form{};
};

struct DeclRefExprDataT {
  std::unique_ptr<ExprDataT> base{};
  std::string qualifier{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
  int64_t decl{};
};

struct OverloadExprDataT {
  std::unique_ptr<ExprDataT> base{};
  std::string qualifier{};
  std::string name{};
  std::vector<int64_t> unresolved_decls{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct CXXConstructExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_elidable{};
  bool requires_zero_initialization{};
  bool is_list_initialization{};
  bool is_std_list_initialization{};
  ConstructionKind construction_kind{};
  bool is_temporary_object{};
  int64_t constructor_decl{};
};

struct CXXTemporaryObjectExprDataT {
  std::unique_ptr<CXXConstructExprDataT> base{};
};

struct MemberExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_arrow{};
  std::string member_name{};
  int64_t member_decl{};
  int64_t found_decl{};
  AccessSpecifier found_decl_access_specifier{};
};

struct MaterializeTemporaryExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int64_t extending_decl{};
};

struct BinaryOperatorDataT {
  std::unique_ptr<ExprDataT> base{};
  BinaryOperatorKind op{};
};

struct UnresolvedMemberExprDataT {
  std::unique_ptr<OverloadExprDataT> base{};
};

struct UnresolvedLookupExprDataT {
  std::unique_ptr<OverloadExprDataT> base{};
  bool requires_adl{};
};

struct CallExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int64_t direct_callee{};
};

struct CXXMemberCallExprDataT {
  std::unique_ptr<CallExprDataT> base{};
  int64_t method_decl{};
};

struct CXXTypeidExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_type_operand{};
  int64_t operand{};
};

struct ExplicitCastExprDataT {
  std::unique_ptr<CastExprDataT> base{};
  int64_t type_as_written{};
};

struct CXXNamedCastExprDataT {
  std::unique_ptr<ExplicitCastExprDataT> base{};
  std::string cast_name{};
};

struct CXXDependentScopeMemberExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_arrow{};
  std::string member_name{};
  bool is_implicit_access{};
  std::string qualifier{};
  bool has_template_keyword{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct UnaryOperatorDataT {
  std::unique_ptr<ExprDataT> base{};
  UnaryOperatorKind op{};
  UnaryOperatorPosition position{};
};

struct UnaryExprOrTypeTraitExprDataT {
  std::unique_ptr<ExprDataT> base{};
  UnaryExprOrTypeTrait kind{};
  bool is_argument_type{};
  int64_t arg_type{};
  std::string source_literal{};
};

struct CXXNewExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_global{};
  bool is_array{};
  bool initialization_present{};
  NewInitStyle init_style{};
  int64_t initializer{};
  int64_t construct_expr{};
  int64_t array_size{};
  int64_t operator_new{};
};

struct CXXDeleteExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_global{};
  bool is_array{};
  bool is_array_as_written{};
};

struct OffsetOfExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int64_t source_type{};
  std::vector<std::unique_ptr<OffsetOfComponentT>> components{};
};

struct LambdaExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_generic_lambda{};
  bool is_mutable{};
  bool has_explicit_parameters{};
  bool has_explicit_result_type{};
  LambdaCaptureDefault capture_default{};
  int64_t lambda_class{};
  std::vector<LambdaCaptureKind> capture_kinds{};
};

struct PredefinedExprDataT {
  std::unique_ptr<ExprDataT> base{};
  PredefinedIdType predefined_type{};
};

struct SizeOfPackExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool is_partially_substituted{};
  int64_t pack{};
  std::vector<std::unique_ptr<TemplateArgumentT>> partial_arguments{};
};

struct ArrayInitLoopExprDataT {
  std::unique_ptr<ExprDataT> base{};
};

struct DesignatedInitExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool uses_gnu_syntax{};
  std::vector<std::unique_ptr<DesignatorT>> designators{};
};

struct DependentScopeDeclRefExprDataT {
  std::unique_ptr<ExprDataT> base{};
  std::string decl_name{};
  std::string qualifier{};
  bool has_template_keyword{};
  std::vector<std::unique_ptr<TemplateArgumentT>> template_arguments{};
};

struct CXXNoexceptExprDataT {
  std::unique_ptr<ExprDataT> base{};
  bool value{};
};

struct CXXPseudoDestructorExprDataT {
  std::unique_ptr<ExprDataT> base{};
  std::string qualifier{};
  bool is_arrow{};
  int64_t destroyed_type{};
};

struct PseudoObjectExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int32_t result_expr_index{};
};

struct MSPropertyRefExprDataT {
  std::unique_ptr<ExprDataT> base{};
  int64_t base_expr{};
  int64_t property_decl{};
  bool is_implicit_access{};
  bool is_arrow{};
};

struct StmtDataT {
  std::unique_ptr<NodeDataT> base{};
};

struct LabelStmtDataT {
  std::unique_ptr<StmtDataT> base{};
  int64_t label{};
};

struct GotoStmtDataT {
  std::unique_ptr<StmtDataT> base{};
  int64_t label{};
};

struct AttributedStmtDataT {
  std::unique_ptr<StmtDataT> base{};
  std::vector<int64_t> stmt_attributes{};
};

struct AsmStmtDataT {
  std::unique_ptr<StmtDataT> base{};
  bool is_simple{};
  bool is_volatile{};
  std::vector<std::string> clobbers{};
  std::vector<std::unique_ptr<AsmOutputT>> outputs{};
  std::vector<std::unique_ptr<AsmInputT>> inputs{};
};

struct GCCAsmStmtDataT {
  std::unique_ptr<AsmStmtDataT> base{};
  std::string asm_string{};
};

struct MSAsmStmtDataT {
  std::unique_ptr<AsmStmtDataT> base{};
  std::string asm_string{};
};

struct AttributeDataT {
  std::unique_ptr<NodeDataT> base{};
  AttributeKind kind{};
  bool is_implicit{};
  bool is_inherited{};
  bool is_late_parsed{};
  bool is_pack_expansion{};
};

struct AlignedAttrDataT {
  std::unique_ptr<AttributeDataT> base{};
  std::string spelling{};
  bool is_expression{};
  int64_t alignment{};
};

struct OpenCLUnrollHintAttrDataT {
  std::unique_ptr<AttributeDataT> base{};
  int32_t unroll_hint{};
};

struct FormatAttrDataT {
  std::unique_ptr<AttributeDataT> base{};
  FormatAttrKind type{};
  int32_t format_index{};
  int32_t first_arg{};
};

struct NonNullAttrDataT {
  std::unique_ptr<AttributeDataT> base{};
  std::vector<int32_t> arguments{};
};

struct VisibilityAttrDataT {
  std::unique_ptr<AttributeDataT> base{};
  VisibilityType visibility_type{};
};

struct FileT {
  uint32_t id{};
  std::string path{};
};

struct ChildrenT {
  int64_t node{};
  std::vector<int64_t> children{};
};

struct NodeClassT {
  int64_t node{};
  std::string class_name{};
};

struct TopLevelT {
  TopLevelKind kind{};
  int64_t node{};
};

struct IncludeT {
  std::string source{};
  std::string name{};
  uint32_t line{};
  bool angled{};
};

struct PragmaT {
  std::string source{};
  uint32_t line{};
  uint32_t column{};
};

struct TranslationUnitFileT {
  int32_t id{};
  std::string path{};
};

struct CounterT {
  int32_t value{};
};

struct LanguageT {
  std::string file{};
  bool line_comment{};
  bool gnu_inline{};
  bool c99{};
  bool c11{};
  bool c_plus_plus{};
  bool c_plus_plus_11{};
  bool c_plus_plus_14{};
  bool c_plus_plus_17{};
  bool c_plus_plus_20{};
  bool c_plus_plus_23{};
  bool c_plus_plus_26{};
  bool has_digraphs{};
  bool is_gnu{};
  bool hex_floats{};
  bool open_cl{};
  uint32_t open_cl_version{};
  bool native_half_type{};
  bool cuda{};
  bool has_bool{};
  bool has_half{};
  bool has_wchar{};
  uint32_t char_width{};
  uint32_t float_width{};
  uint32_t double_width{};
  uint32_t long_double_width{};
  uint32_t bool_width{};
  uint32_t short_width{};
  uint32_t int_width{};
  uint32_t long_width{};
  uint32_t long_long_width{};
};

struct NodeT {
  int64_t id{};
  std::string class_name{};
  UnionValue payload;
};

using TemplateValue = UnionValue;
using TemplateNameValue = UnionValue;
using InitializerTarget = UnionValue;
using ExceptionDetails = UnionValue;
using OffsetValue = UnionValue;
using DesignatorValue = UnionValue;
using NestedNameValue = UnionValue;
using DeclPayload = UnionValue;
using TypePayload = UnionValue;
using NodePayload = UnionValue;

} // namespace astwire::v1obj
