name: Release binaries

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

env:
  CLANG_VERSION: "16"

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install LLVM/Clang ${{ env.CLANG_VERSION }} (apt.llvm.org)
        run: |
            set -eux
            sudo apt-get update
            sudo apt-get install -y wget software-properties-common gnupg lsb-release
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh ${CLANG_VERSION}
            sudo apt-get install -y \
                llvm-${CLANG_VERSION}-dev \
                libclang-${CLANG_VERSION}-dev \
                lld-${CLANG_VERSION} \
                cmake ninja-build \
                zlib1g-dev libedit-dev libzstd-dev libpolly-${CLANG_VERSION}-dev

      - name: Configure (CMake)
        run: |
            cmake -S . -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DLLVM_DIR=/usr/lib/llvm-${CLANG_VERSION}/lib/cmake/llvm \
                -DClang_DIR=/usr/lib/llvm-${CLANG_VERSION}/lib/cmake/clang

      - name: Build
        run: cmake --build build --config Release -- -v

      - name: Package artifact
        run: |
            set -eux
            cp build/tool ./clang-dumper
            tar -czf clang-dumper-linux.tar.gz clang-dumper

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
              clang-dumper-linux.tar.gz

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up MSYS2 with MinGW LLVM/Clang and tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            cmake
            ninja
            zip
            mingw-w64-x86_64-llvm
            mingw-w64-x86_64-llvm-libs
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-clang-tools-extra
            mingw-w64-x86_64-nodejs
            mingw-w64-x86_64-libedit
            mingw-w64-x86_64-zstd
            mingw-w64-x86_64-zlib

      - name: Configure (CMake)
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          MINGW_BASEDIR="C:/msys64/mingw64"
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DMINGW_BASEDIR="${MINGW_BASEDIR}" \
            -DLLVM_DIR="${MINGW_BASEDIR}/lib/cmake/llvm" \
            -DClang_DIR="${MINGW_BASEDIR}/lib/cmake/clang"

      - name: Build
        shell: msys2 {0}
        run: cmake --build build --config Release -- -v

      - name: Package artifact
        shell: msys2 {0}
        run: |
          set -eux
          cd build
          test -f tool.exe
          zip -9 ../clang-dumper-windows.zip tool.exe

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            clang-dumper-windows.zip

  build-macos:
    name: Build (macOS)
    runs-on: macos-13
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install LLVM/Clang ${{ env.CLANG_VERSION }} (brew)
        run: |
          set -eux
          brew update
          brew install llvm@${CLANG_VERSION} ninja zstd libedit
          echo "LLVM_PREFIX=$(brew --prefix llvm@${CLANG_VERSION})" >> $GITHUB_ENV

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DLLVM_DIR="${LLVM_PREFIX}/lib/cmake/llvm" \
              -DClang_DIR="${LLVM_PREFIX}/lib/cmake/clang"

      - name: Build
        run: cmake --build build --config Release -- -v

      - name: Package artifact
        run: |
          set -eux
          cp build/tool ./clang-dumper
          tar -czf clang-dumper-macos.tar.gz clang-dumper

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            clang-dumper-macos.tar.gz

  finalize:
    name: Finalize or cancel release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: ${{ always() }}
    steps:
      - name: Cancel (delete) the release on failure
        if: ${{ needs.build-linux.result != 'success' || needs.build-windows.result != 'success' || needs.build-macos.result != 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          set -eux
          sudo apt-get update && sudo apt-get install -y jq
          api="https://api.github.com/repos/${GITHUB_REPOSITORY}"
          rel_json=$(curl -sS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "${api}/releases/tags/${TAG_NAME}")
          id=$(echo "$rel_json" | jq -r '.id')
          echo "Deleting release ${TAG_NAME} (id=${id}) due to failed build(s)."
          curl -sS -X DELETE -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "${api}/releases/${id}"
          echo "Release deleted."
      - name: Success note
        if: ${{ needs.build-linux.result == 'success' && needs.build-windows.result == 'success' && needs.build-macos.result == 'success' }}
        run: echo "All builds succeeded and assets are attached to the release."
